### ISSUE TITLE
cov_pca error: TypeError: an integer is required

### ISSUE THREAD

**Issue by Quicken-up** [Ecogenomics/CheckM#109]
I got checkm coverage to run, using 42 indexed bam files for a 42 sample coassembly (metabat binned contigs over 2kb). This generated a 2.5GB TSV. I then tried to run cov_pca as follows:
checkm cov_pca --image_type pdf -x fa ./min2k_ensemble ./min2k_ensemble/plots min2k_ensemble_coverage.tsv

It gives the following traceback:

Computing PCA of coverage profiles. Any help appreciated.

Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/checkm_env/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/checkm_env/lib/python2.7/site-packages/checkm/main.py", line 1275, in parseOptions
    self.coveragePcaPlot(options)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/checkm_env/lib/python2.7/site-packages/checkm/main.py", line 606, in coveragePcaPlot
    pc, variance = pca.pcaMatrix(coverageProfiles, fraction=1.0, bCenter=True, bScale=False)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/checkm_env/lib/python2.7/site-packages/checkm/PCA.py", line 62, in pcaMatrix
    Center(A, bScale)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/checkm_env/lib/python2.7/site-packages/checkm/PCA.py", line 112, in __init__
    self.mean = A.mean(axis=axis)
  File "/exports/cmvm/eddie/eb/groups/watson_grp/software/myanaconda/checkm_env/lib/python2.7/site-packages/numpy/core/_methods.py", line 70, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: an integer is required

**Comment by dparks1134** [comment]
Hello. I haven't run across this issue before. Can you see if this still happens with just 2 BAM files and perhaps on just a subset of your bins? If you can send me a smaller TSV file, I can look into what is happening.

**Comment by dparks1134** [comment]
Marking as resolved as issue has not been reported by others.

**Comment by johnne** [comment]
Hi,

I'm getting this exact error as well.

I've got 42 genome bins with BAM files from 4 paired-end samples. 

`checkm coverage`

works without a problem but running:

`checkm cov_pca temp/good_mags.tab/fna/ results/MAGs/checkm/Prokaryote/ results/MAGs/checkm/Prokaryote/coverage.tsv`

results in

> Computing PCA of coverage profiles.
Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/home/john/lib/miniconda2/envs/checkm/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/home/john/lib/miniconda2/envs/checkm/lib/python2.7/site-packages/checkm/main.py", line 1279, in parseOptions
    self.coveragePcaPlot(options)
  File "/home/john/lib/miniconda2/envs/checkm/lib/python2.7/site-packages/checkm/main.py", line 610, in coveragePcaPlot
    pc, variance = pca.pcaMatrix(coverageProfiles, fraction=1.0, bCenter=True, bScale=False)
  File "/home/john/lib/miniconda2/envs/checkm/lib/python2.7/site-packages/checkm/PCA.py", line 62, in pcaMatrix
    Center(A, bScale)
  File "/home/john/lib/miniconda2/envs/checkm/lib/python2.7/site-packages/checkm/PCA.py", line 112, in __init__
    self.mean = A.mean(axis=axis)
  File "/home/john/lib/miniconda2/envs/checkm/lib/python2.7/site-packages/numpy/core/_methods.py", line 70, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: an integer is required

**Comment by dparks1134** [comment]
Are you able to send me the data that is causing this issue? If so, I can look into what is causing CheckM to fail.

**Comment by johnne** [comment]
@dparks1134 Thanks for the reply. Attached is the coverage file from `checkm coverage`
[coverage.tsv.gz](https://github.com/Ecogenomics/CheckM/files/1492797/coverage.tsv.gz)

**Comment by dparks1134** [comment]
Hello. Sorry, I missed you reply. I would also need the bins in order to replicate the error. I tried creating some "fake" bins, but they all worked fine.

**Comment by Thomieh73** [comment]
Hi Donovan,

I am getting the same issue for the command:
```
 checkm cov_pca -x fasta --image_type png --dpi 600 good_bins cov_pca_plots checkm_coverage.txt
```
The same thing also happens with the command: `checkm tetra_pca`.

To test if it was my data, I have taken a fasta file with the _Thermosipho africanus_ genome and I ran the following commands on that:

```
checkm tetra -t 32 test_bins/Tafricanus_TCF52B_NC_011653.fna test_bins_tetra_freq.tsv

checkm tetra_pca -x fna test_bins test_bins_plots test_bins_tetra_freq.tsv
```

This is the output I get:
```
Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/usit/abel/u1/thhaverk/tools/anaconda3/envs/checkm_env/bin/checkm", line 709, in <module>
    checkmParser.parseOptions(args)
  File "/usit/abel/u1/thhaverk/tools/anaconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/main.py", line 1286, in parseOptions
    self.tetraPcaPlot(options)
  File "/usit/abel/u1/thhaverk/tools/anaconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/main.py", line 565, in tetraPcaPlot
    seqIds, pc, variance = pca.pcaFile(options.tetra_profile, fraction=1.0, bCenter=True, bScale=False)
  File "/usit/abel/u1/thhaverk/tools/anaconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/PCA.py", line 53, in pcaFile
    self.pcaMatrix(data, fraction, bCenter, bScale)
  File "/usit/abel/u1/thhaverk/tools/anaconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/PCA.py", line 62, in pcaMatrix
    Center(A, bScale)
  File "/usit/abel/u1/thhaverk/tools/anaconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/PCA.py", line 112, in __init__
    self.mean = A.mean(axis=axis)
  File "/usit/abel/u1/thhaverk/tools/anaconda3/envs/checkm_env/lib/python2.7/site-packages/numpy/core/_methods.py", line 70, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: an integer is required
```

This suggests at least that a different dataset is causing a similar error...

I have checkm running in a conda virtual environment on a computing cluster. 
Furthermore, when I run refineM, I get similar issues when asking for plots.
