### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by samfux84** [Ecogenomics/CheckM#112]
```
[sfux@euler01 ~]$ module load new gcc/4.8.2 gdc prodigal/2.6.3 hmmer/3.1 python/2.7.12 xz/5.2.2               
Autoloading openblas/0.2.13_seq
[sfux@euler01 ~]$ checkm test testresults                                                              

*******************************************************************************
[CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
*******************************************************************************

[Step 1]: Verifying tree command.

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
  Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 1 bins into the genome tree with pplacer (be patient).
sh: line 1:  8588 Killed                  pplacer -j 1 -c /cluster/apps/python/2.7.12/x86_64/lib64/python2.7/site-packages/checkm/data/genome_tree/genome_tree_reduced.refpkg -o testresults/results/storage/tree/concatenated.pplacer.json testresults/results/storage/tree/concatenated.fasta > testresults/results/storage/tree/pplacer.out
Uncaught exception: Sys_error("testresults/results/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("testresults/results/storage/tree/concatenated.pplacer.json: No such file or directory")

  { Current stage: 0:01:03.214 || Total: 0:01:03.214 }

  [Passed]


[Step 2]: Verifying tree_qa command.

*******************************************************************************
 [CheckM - tree_qa] Assessing phylogenetic markers found in each bin.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.


Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/cluster/apps/python/2.7.12/x86_64/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/cluster/apps/python/2.7.12/x86_64/lib64/python2.7/site-packages/checkm/main.py", line 1311, in parseOptions
    self.test(options)
  File "/cluster/apps/python/2.7.12/x86_64/lib64/python2.7/site-packages/checkm/main.py", line 1198, in test
    verifyEcoli.run(self, options.output_dir)
  File "/cluster/apps/python/2.7.12/x86_64/lib64/python2.7/site-packages/checkm/test/test_ecoli.py", line 76, in run
    parser.treeQA(options)
  File "/cluster/apps/python/2.7.12/x86_64/lib64/python2.7/site-packages/checkm/main.py", line 190, in treeQA
    treeParser.printSummary(options.out_format, options.tree_folder, RP, options.bTabTable, options.file, binStats)
  File "/cluster/apps/python/2.7.12/x86_64/lib64/python2.7/site-packages/checkm/treeParser.py", line 45, in printSummary
    self.reportBinTaxonomy(outDir, resultsParser, bTabTable, outFile, binStats, bLineageStatistics=False)
  File "/cluster/apps/python/2.7.12/x86_64/lib64/python2.7/site-packages/checkm/treeParser.py", line 633, in reportBinTaxonomy
    binIdToTaxonomy = self.getBinTaxonomy(outDir, binIds)
  File "/cluster/apps/python/2.7.12/x86_64/lib64/python2.7/site-packages/checkm/treeParser.py", line 191, in getBinTaxonomy
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "build/bdist.linux-x86_64/egg/dendropy/datamodel/basemodel.py", line 215, in get_from_path
  File "build/bdist.linux-x86_64/egg/dendropy/utility/filesys.py", line 60, in pre_py34_open
IOError: [Errno 2] No such file or directory: 'testresults/results/storage/tree/concatenated.tre'
[sfux@euler01 ~]$ ls testresults/results/storage/tree/concatenated.tre
ls: cannot access testresults/results/storage/tree/concatenated.tre: No such file or directory
[sfux@euler01 ~]$
```

**Comment by dparks1134** [comment]
Can you confirm that you have sufficient memory to run CheckM? Even with the reduced tree it requires 16GB.

**Comment by samfux84** [comment]
I was running the tests in a VM with 32 GB of memory. I will run the test again on a computer with 256 GB of memory and then get back to you as soon as the test is done.

**Comment by samfux84** [comment]
When running the same test on a computer with 256 GB of memory, the error does not occur anymore:

```
[sfux@e1286 ~]$ module load new gcc/4.8.2 gdc prodigal/2.6.3 hmmer/3.1 python/2.7.12 xz/5.2.2             
Autoloading openblas/0.2.13_seq
[sfux@e1286 ~]$ export PYTHONPATH=/cluster/home/sfux/python/lib64/python2.7/site-packages/            
[sfux@e1286 ~]$ checkm test testresults

*******************************************************************************
[CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
*******************************************************************************

[Step 1]: Verifying tree command.

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
  Saving HMM info to file.

  Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.

  Extracting marker genes to align.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
  Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
  Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.

  Reading marker alignment files.
  Concatenating alignments.
  Placing 1 bins into the genome tree with pplacer (be patient).

  { Current stage: 0:02:41.684 || Total: 0:02:41.684 }

  [Passed]


[Step 2]: Verifying tree_qa command.

*******************************************************************************
 [CheckM - tree_qa] Assessing phylogenetic markers found in each bin.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

  QA information written to: testresults/results/tree_qa_test.tsv

  { Current stage: 0:00:00.998 || Total: 0:02:42.683 }

  [Passed]


[Step 3]: Verifying lineage_set command.

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

  Determining marker sets for each genome bin.
    Finished processing 1 of 1 (100.00%) bins (current: 637000110).

  Marker set written to: testresults/results/lineage_set_test.tsv

  { Current stage: 0:00:02.026 || Total: 0:02:44.709 }

*******************************************************************************
 [CheckM - lineage_set] Inferring lineage-specific marker sets.
*******************************************************************************

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

  Determining marker sets for each genome bin.
    Finished processing 1 of 1 (100.00%) bins (current: 637000110).

  Marker set written to: testresults/results/lineage_set_test.tsv

  { Current stage: 0:00:01.455 || Total: 0:02:46.165 }

  [Passed]


[Step 4]: Verifying analyze command.

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 1 bins with 1 threads:
User defined signal 2ng 0 of 1 (0.00%) bins.
[sfux@euler09 ~]$
```

Thank you for your help

**Comment by dparks1134** [comment]
Issue was related to available memory.
