### ISSUE TITLE
checkm tree: isNucleotide ZeroDivisionError

### ISSUE THREAD

**Issue by snayfach** [Ecogenomics/CheckM#116]
I'm running CheckM v1.0.7 on 250 genomes with the following command:

`checkm tree $OUTDIR/genomes $OUTDIR/checkm --threads $NTHREADS --pplacer_threads 1`

Which produces the following error:

```
*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************


Unexpected error: <type 'exceptions.ZeroDivisionError'>
Traceback (most recent call last):
  File "/global/homes/s/snayfach/.conda/envs/checkm/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/global/homes/s/snayfach/.conda/envs/checkm/lib/python2.7/site-packages/checkm/main.py", line 1223, in parseOptions
    self.tree(options)
  File "/global/homes/s/snayfach/.conda/envs/checkm/lib/python2.7/site-packages/checkm/main.py", line 113, in tree
    if not checkNuclotideSeqs(binFiles):
  File "/global/homes/s/snayfach/.conda/envs/checkm/lib/python2.7/site-packages/checkm/util/seqUtils.py", line 138, in checkNuclotideSeqs
    if not isNucleotide(seq_file):
  File "/global/homes/s/snayfach/.conda/envs/checkm/lib/python2.7/site-packages/checkm/util/seqUtils.py", line 71, in isNucleotide
    if float(nt_bases) / len(seq) >= req_perc:
ZeroDivisionError: float division by zero
```

There appears to be some issue with one or more input genomes. CheckM should detect and report this issue (whatever it is).

Thanks,
Stephen

**Comment by dparks1134** [comment]
Hey Stephen,

Is this the same 250 genomes you reported before? 

Agreed CheckM should catch this case and fail gracefully. It would appear that you have a bin/genomes with a zero length sequence in it, i.e.:

>seq_with_no_nucleotide_data
>next_seq
ACGT

Cheers,
Donovan

**Comment by snayfach** [comment]
Thanks for the reply, Donovan.

Let me check to confirm this is the case before closing the issue. And, no these are a different set of genomes from my other issue.

**Comment by snayfach** [comment]
Yep, there were some genomes with headers but no sequences
