### ISSUE TITLE
IOError: [Errno 122] Disk quota exceeded

### ISSUE THREAD

**Issue by Rebeccabengtsson** [Ecogenomics/CheckM#121]
Hello,

I have successfully installed checkm using pip install checkm-genome 

But when I run checkm error with Disk quota exceeded occurs 

Traceback (most recent call last):
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/bin/checkm", line 36, in <module>
    from checkm import main
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/checkm/main.py", line 49, in <module>
    from checkm.plot.gcPlots import GcPlots
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/checkm/plot/gcPlots.py", line 24, in <module>
    from AbstractPlot import AbstractPlot
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/checkm/plot/AbstractPlot.py", line 22, in <module>
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 32, in <module>
    from matplotlib.backend_bases import (
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 64, in <module>
    import matplotlib.textpath as textpath
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/matplotlib/textpath.py", line 17, in <module>
    import matplotlib.font_manager as font_manager
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1454, in <module>
    _rebuild()
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/matplotlib/font_manager.py", line 1438, in _rebuild
    json_dump(fontManager, _fmcache)
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/lib/python2.7/site-packages/matplotlib/font_manager.py", line 966, in json_dump
    json.dump(data, fh, cls=JSONEncoder, indent=2)
  File "/exports/cmvm/eddie/eb/groups/taitali_r43336/SOFTWARE/Python-2.7.9/Lib/json/__init__.py", line 190, in dump
    fp.write(chunk)
IOError: [Errno 122] Disk quota exceeded

But I have plenty of disk space 

[v1rbeng2@node1h21 Python-2.7.9]$ df -h ./
Filesystem      Size  Used Avail Use% 
/dev/fs8        880G  520G  361G  59% 

Can you tell me what is going on and how to troubleshoot? 

Regards
Rebecca

**Comment by dparks1134** [comment]
Hello Rebecca,

CheckM writes data to the default temporary directory of your system. Perhaps you don't have sufficient space in this directory. You can change the temporary directory with the --tmpdir flag.

Cheers,
Donovan

**Comment by Rebeccabengtsson** [comment]
Thanks for your reply Donovan, I just tried using the --tmpdir flag as well as export tmpdir but im still getting the same error

**Comment by dparks1134** [comment]
Perhaps you are exceeding the amount of disk space allocated to your home directory or account? The system may have lots of disk space, but your personal allocation be limited to a specific amount.

**Comment by Rebeccabengtsson** [comment]
I emptied my home directory folder and now its working fine, I guess the --tmpdir flag didn't work and checkm was still trying to build tmp in the default temporary directory.
