### ISSUE TITLE
tree_qa error: AttributeError: 'NoneType' object has no attribute 'label'

### ISSUE THREAD

**Issue by snayfach** [Ecogenomics/CheckM#137]
Hi Donovan,

I'm getting the following error for the first time using the default command:
```
*******************************************************************************
 [CheckM - tree_qa] Assessing phylogenetic markers found in each bin.
*******************************************************************************
  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 41 (2.44%) bins
...
Finished parsing hits for 41 of 41 (100.00%) bins.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/global/homes/s/snayfach/.conda/envs/my_root/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/global/homes/s/snayfach/.conda/envs/my_root/lib/python2.7/site-packages/checkm/main.py", line 1225, in parseOptions
    self.treeQA(options)
  File "/global/homes/s/snayfach/.conda/envs/my_root/lib/python2.7/site-packages/checkm/main.py", line 190, in treeQA
    treeParser.printSummary(options.out_format, options.tree_folder, RP, options.bTabTable, options.file, binStats)
  File "/global/homes/s/snayfach/.conda/envs/my_root/lib/python2.7/site-packages/checkm/treeParser.py", line 45, in printSummary
    self.reportBinTaxonomy(outDir, resultsParser, bTabTable, outFile, binStats, bLineageStatistics=False)
  File "/global/homes/s/snayfach/.conda/envs/my_root/lib/python2.7/site-packages/checkm/treeParser.py", line 633, in reportBinTaxonomy
    binIdToTaxonomy = self.getBinTaxonomy(outDir, binIds)
  File "/global/homes/s/snayfach/.conda/envs/my_root/lib/python2.7/site-packages/checkm/treeParser.py", line 216, in getBinTaxonomy
    domainNode = self.__findDomainNode(node)
  File "/global/homes/s/snayfach/.conda/envs/my_root/lib/python2.7/site-packages/checkm/treeParser.py", line 244, in __findDomainNode
    if curNode.label:
AttributeError: 'NoneType' object has no attribute 'label'
```

The genomes I'm using can be found in the following link:
https://www.dropbox.com/sh/3jyk8i5uz1cycfx/AAAfZj5la76sW_N8nX2Kmq2ka?dl=0

**Comment by dparks1134** [comment]
Hello. This issue should be resolved in the latest version of CheckM (v1.0.11).

**Comment by snayfach** [comment]
Do you recall what the issue was? It must be related to the genomes I'm using - 99% of other genomes had no issues

**Comment by snayfach** [comment]
Never mind I see now looking at issue #130. And I'm running v1.0.7 so that makes sense too
