### ISSUE TITLE
minor bug?

### ISSUE THREAD

**Issue by bernt-matthias** [Ecogenomics/CheckM#164]
```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/__checkm-genome@1.0.11/bin/checkm", line 709, in <module>
    checkmParser.parseOptions(args)
  File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/__checkm-genome@1.0.11/lib/python2.7/site-packages/checkm/main.py", line 1253, in parseOptions
    self.tree(options)
  File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/__checkm-genome@1.0.11/lib/python2.7/site-packages/checkm/main.py", line 156, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/__checkm-genome@1.0.11/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 104, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/__checkm-genome@1.0.11/lib/python2.7/site-packages/checkm/main.py", line 1213, in parseOptions
    if options.bVerbose:
AttributeError: 'Namespace' object has no attribute 'bVerbose'
```

**Comment by dparks1134** [comment]
This should be addressed in v1.0.12 which will be released later today.
