### ISSUE TITLE
Error when updating data when changing data directory

### ISSUE THREAD

**Issue by ctSkennerton** [Ecogenomics/CheckM#18]
I wanted to change the data directory for my checkM installation (version 0.9.4), which resulted in checkM wanting to update the data. It fails with an OSError
```
checkm data setRoot

*******************************************************************************
 [CheckM - data] Check for database updates. [setRoot]
*******************************************************************************

Where should CheckM store it's data?
Please specify a location or type 'abort' to stop trying: 
/export/data1/db/checkm/
Path [/export/data1/db/checkm] exists and you have permission to write to this folder
(re) creating manifest file (please be patient)
****************************************************************
10 new file(s) to be downloaded from source
2 existing file(s) to be updated
138.02 MB will need to be downloaded
Confirm you want to download this data
Changes *WILL* be permanent
Continue? (y,n) : y
****************************************************************
****************************************************************
The following 6 file(s) are scheduled to be removed
genome_tree/genome_tree_prok.refpkg
genome_tree/genome_tree_prok.refpkg/genome_tree.derep.log
genome_tree/genome_tree_prok.refpkg/genome_tree.final.tre
genome_tree/genome_tree_prok.refpkg/phylo_modelytLSd6.json
genome_tree/genome_tree_prok.refpkg/CONTENTS.json
genome_tree/genome_tree_prok.refpkg/genome_tree.concatenated.derep.fasta
Confirm you want to delete these files
Changes *WILL* be permanent
Delete files? (y,n) : y
****************************************************************
/export/data1/db/checkm/genome_tree/genome_tree_prok.refpkg/genome_tree.derep.log

Unexpected error: <type 'exceptions.OSError'>
Traceback (most recent call last):
  File "/export/data1/sw/checkm/0.9.4/bin/checkm", line 657, in <module>
    checkmParser.parseOptions(args)
  File "/export/data1/sw/checkm/0.9.4/lib/python2.7/site-packages/checkm/main.py", line 1134, in parseOptions
    self.updateCheckM_DB(options)
  File "/export/data1/sw/checkm/0.9.4/lib/python2.7/site-packages/checkm/main.py", line 84, in updateCheckM_DB
    self.DBM.runAction(options.action)
  File "/export/data1/sw/checkm/0.9.4/lib/python2.7/site-packages/checkm/checkmData.py", line 141, in runAction
    path = self.setRoot()
  File "/export/data1/sw/checkm/0.9.4/lib/python2.7/site-packages/checkm/checkmData.py", line 184, in setRoot
    self.update()
  File "/export/data1/sw/checkm/0.9.4/lib/python2.7/site-packages/checkm/checkmData.py", line 164, in update
    prompt=True)
  File "/export/data1/sw/screamingbackpack/0.2.2/lib/python2.7/site-packages/screamingbackpack/manifestManager.py", line 278, in updateManifest
    os.remove(delete)
OSError: [Errno 2] No such file or directory: '/export/data1/db/checkm/genome_tree/genome_tree_prok.refpkg/genome_tree.derep.log'
```

**Comment by dparks1134** [comment]
Hey Connor,

Can you check to see if the offending file actually exists:
/export/data1/db/checkm/genome_tree/genome_tree_prok.refpkg/genome_tree.derep.log

Cheers,
Donovan

**Comment by ctSkennerton** [comment]
The whole directory `genome_tree_prok.refpkg` doesn't exist, I'll try the manual download

**Comment by ctSkennerton** [comment]
Yo, manual download seemed to work
