### ISSUE TITLE
Odd issue when running checkm lineage_wf

### ISSUE THREAD

**Issue by mb1069** [Ecogenomics/CheckM#201]
Running the following command causes an issue;
`checkm lineage_wf -x fa binsA binsA.checkm -t 4 --tmpdir binsA.tmp --pplacer_threads 4 --reduced_tree
`
```
*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 2 bins with 1 threads:
Process SyncManager-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/opt/conda/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python2.7/multiprocessing/managers.py", line 550, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/opt/conda/lib/python2.7/multiprocessing/managers.py", line 162, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/opt/conda/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/opt/conda/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/opt/conda/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/opt/conda/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/opt/conda/lib/python2.7/site-packages/checkm/main.py", line 1251, in parseOptions
    self.tree(options)
  File "/opt/conda/lib/python2.7/site-packages/checkm/main.py", line 133, in tree
    options.bCalledGenes)
  File "/opt/conda/lib/python2.7/site-packages/checkm/markerGeneFinder.py", line 67, in find

Unexpected error: <type 'exceptions.EOFError'>
    binIdToModels = mp.Manager().dict()
  File "/opt/conda/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/opt/conda/lib/python2.7/multiprocessing/managers.py", line 528, in start
    self._address = reader.recv()
EOFError

```
This can be avoided by removing the --tmpdir option,
See the below issue for the original source in metaWRAP
https://github.com/bxlab/metaWRAP/issues/191#issue-453645918

**Comment by dparks1134** [comment]
I think this issue is because `--tmpdir` needs to point to an existing directory.
