### ISSUE TITLE
ImportError: libcrypto.so.1.0.0:

### ISSUE THREAD

**Issue by singhbhavya** [Ecogenomics/CheckM#216]
Hi! I just installed checkm using Bioconda, and received the following error when I did `checkm data setRoot`. Any help would be appreciated!

```
Traceback (most recent call last):
  File "/home/bsingh/bin/anaconda2/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 28, in <module>
    from checkm.resultsParser import ResultsParser
  File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/checkm/resultsParser.py", line 34, in <module>
    from checkm.coverage import Coverage
  File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/checkm/coverage.py", line 30, in <module>
    import pysam
  File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by dparks1134** [comment]
Hello. I don't maintain the Bioconda install. I'm not sure how to determine who does. :)

**Comment by singhbhavya** [comment]
Hi there! So sorry to bother you again. I uninstalled checkm through anaconda, and then re-installed the regular way.

I ran `checkm data setRoot /home/bsingh/bin/checkm/ `and got the following error again:

  
```
It seems that the CheckM data folder has not been set yet or has been removed. Please run 'checkm data setRoot'.

Path [/home/bsingh/.checkm] has been created and you have permission to write to this folder.
(re) creating manifest file (please be patient).
Traceback (most recent call last):
  File "/home/bsingh/bin/anaconda2/bin/checkm", line 36, in <module>
    from checkm import main
  File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 28, in <module>
    from checkm.resultsParser import ResultsParser
  File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/checkm/resultsParser.py", line 34, in <module>
    from checkm.coverage import Coverage
  File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/checkm/coverage.py", line 30, in <module>
    import pysam
  File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by singhbhavya** [comment]
Hi! So sorry for bothering you again. I uninstalled the Bioconda checkm and re-installed using pip. This is the error I'm getting now:

```
 File "/home/bsingh/bin/anaconda2/lib/python2.7/site-packages/checkm/main.py", line 25, in <module>
    from checkm.defaultValues import DefaultValues
ImportError: No module named defaultValues

```

**Comment by singhbhavya** [comment]
I am so sorry, I keep bothering you! I uninstalled the Bioconda checkm, and have re-installed using pip. Still getting this error:

```
 File "/home/bsingh/.local/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by dparks1134** [comment]
Hello. This seems to be a dependency of pysam. Can you try installing pysam separately (`pip install pysam`) and see if this addresses the issue?

**Comment by Thexiyang** [comment]
Was this issue solved? Same issue to me. `pip install pysam` does not solve the issue.

**Comment by singhbhavya** [comment]
Hi @Thexiyang! CheckM worked for me after I:
- Removed it from anaconda
- Downloaded CheckM locally and also downloaded all the dependencies 
- **Deactivated any running anaconda environment** 

If anaconda is activated, I believe the program partially uses the anaconda library to fulfill dependency requirements and partially uses your locally downloaded software. If your anaconda uses a different version of python, you end up seeing the problem with `pip install pysam`

Let me know if this solution works for you!

**Comment by siolybecerra** [comment]
> Hi @Thexiyang! CheckM worked for me after I:
> 
> * Removed it from anaconda
> * Downloaded CheckM locally and also downloaded all the dependencies
> * **Deactivated any running anaconda environment**
> 
> If anaconda is activated, I believe the program partially uses the anaconda library to fulfill dependency requirements and partially uses your locally downloaded software. If your anaconda uses a different version of python, you end up seeing the problem with `pip install pysam`
> 
> Let me know if this solution works for you!

Thanks for sharing your solution. Finally, this solution worked for me! 🙌🏻
