### ISSUE TITLE
plot_dir option missing (duplicate output_dir)

### ISSUE THREAD

**Issue by Finesim97** [Ecogenomics/CheckM#217]
Hey,
While using CheckM (Installed via Conda v1.0.16), I wanted to take a look at the plots it can provide, but im getting this exception for the plot commands.
```
(checkm)me@remote:pathhere$ checkm gc_plot -x fa ../output/Binning/Weurt/bins . 2
[2019-08-10 00:22:07] INFO: CheckM v1.0.16
[2019-08-10 00:22:07] INFO: checkm gc_plot -x fa ../output/Binning/Weurt/bins . 2
[2019-08-10 00:22:07] INFO: [CheckM - gc_plot] Creating GC histogram and delta-GC plot.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/nfs/home/btbi/l/lu6085/miniconda3/envs/checkm/bin/checkm", line 714, in <module>
    checkmParser.parseOptions(args)
  File "/nfs/home/btbi/l/lu6085/miniconda3/envs/checkm/lib/python2.7/site-packages/checkm/main.py", line 1153, in parseOptions
    self.gcPlot(options)
  File "/nfs/home/btbi/l/lu6085/miniconda3/envs/checkm/lib/python2.7/site-packages/checkm/main.py", line 414, in gcPlot
    makeSurePathExists(options.plot_dir)
AttributeError: 'Namespace' object has no attribute 'plot_dir'
```

It seems like one of the two output_dir arguments should be the plot_dir argument. Changing the second one fixes the exception for me.

https://github.com/Ecogenomics/CheckM/blob/64cab7f753e9eea9fc7adc61ccb6a849c87b3c4c/bin/checkm#L327-L331

Have a nice day. 😃

**Comment by Finesim97** [comment]
In codingDensityPlots.py there is still an old reference to out_folder:
https://github.com/Ecogenomics/CheckM/blob/64cab7f753e9eea9fc7adc61ccb6a849c87b3c4c/checkm/plot/codingDensityPlots.py#L55

**Comment by dparks1134** [comment]
Thank you for bringing this to my attention. These issues should be resolved in v1.0.17.

**Comment by rcuadrat** [comment]
I have the same problem. 
AttributeError: 'Namespace' object has no attribute 'plot_dir'

**Comment by rcuadrat** [comment]
Ok, I upgraded to 1.0.17, and now I got another error and I figure out, the help is inverted:

``checkm bin_qa_plot -x .fa qc_checkm_bins_metabat/ all_samples_filtered.fa.metabat-bins plots``

[2019-08-11 08:51:49] INFO: CheckM v1.0.17
[2019-08-11 08:51:49] INFO: checkm bin_qa_plot -x .fa qc_checkm_bins_metabat/storage/ all_samples_filtered.fa.metabat-bins plots
[2019-08-11 08:51:49] INFO: [CheckM - bin_qa_plot] Creating bar plot of bin quality.
[2019-08-11 08:51:49] ERROR: Input file does not exists: plots/bin_stats_ext.tsv

In the help, so far I understood, should be first argument output of checkM, and last argument the plots output folder, but this fails and running the inverted, it works ....

**Comment by rcuadrat** [comment]
Running: 

``checkm bin_qa_plot -x .fa plots all_samples_filtered.fa.metabat-bins qc_checkm_bins_metabat/``
[2019-08-11 08:52:23] INFO: CheckM v1.0.17
[2019-08-11 08:52:23] INFO: checkm bin_qa_plot -x .fa plots all_samples_filtered.fa.metabat-bins qc_checkm_bins_metabat/
[2019-08-11 08:52:23] INFO: [CheckM - bin_qa_plot] Creating bar plot of bin quality.
[2019-08-11 08:52:23] INFO: Calculating AAI between multi-copy marker genes.
[2019-08-11 08:58:33] INFO: Plot written to: qc_checkm_bins_metabat/bin_qa_plot.png

It seems to work, but saving the plots not in the plot output folder, in there, just a log file

**Comment by Finesim97** [comment]
Hey, 
Refactoring dict keys is always so much fun ... , there are still two items, which got the wrong name:

Created a small pull request:
https://github.com/Ecogenomics/CheckM/pull/218

@rcuadrat Your first command (the old argument order) still works, just a small fix is missing. You can fix those lines I changed in my pull request yourself in `<conda env>/lib/python2.7/site-packages/checkm/main.py`

**Comment by dparks1134** [comment]
Thanks for the PR. I am releasing v1.0.18 with this fix now.

**Comment by rcuadrat** [comment]
Great! Thanks guys!!

**Comment by Finesim97** [comment]
My workflow now completes without issues, Thanks 💪
