### ISSUE TITLE
Unexpected error: <type 'exceptions.AttributeError'>

### ISSUE THREAD

**Issue by sarah872** [Ecogenomics/CheckM#220]
Hi,
I am running checkm as
```
python2.7 /apps/checkm/1.0.7/bin/checkm lineage_wf -x fasta spades_assembly checkm_out
```

But I am getting the following error:
```
Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/apps/checkm/1.0.7/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/apps/python2/2.7.15/lib/python2.7/site-packages/checkm/main.py", line 1130, in parseOptions
    options.marker_file = os.path.join(options.output_dir, 'lineage.ms')
AttributeError: 'Namespace' object has no attribute 'output_dir'
```

**Comment by dparks1134** [comment]
Hello. 

Can you please update to the latest version of the CheckM software and see if the issue persists? 

Cheers,
Donovan

**Comment by sarah872** [comment]
Updating solved the issue! Thanks!
