### ISSUE TITLE
par plot error

### ISSUE THREAD

**Issue by blancaverag** [Ecogenomics/CheckM#223]
I am using CheckM v1.0.5 (with hmmer 3.1.b2, prodigal 2.6.3 and pplacer v1.1.alpha17-6-g5cecf99).

When running the par_plot command I run into a problem I am not able to figure out by myself.

```
checkm par_plot -xfa par_plot/ binsO/ plots/ coverage_bins2.TSV 

*******************************************************************************
 [CheckM - par_plot] Creating parallel coordinate plot of GC and coverage.
*******************************************************************************

  Calculating sequence statistics for each bin.

Unexpected error: <type 'exceptions.UnboundLocalError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 1271, in parseOptions
    self.parallelCoordPlot(options)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 798, in parallelCoordPlot
    seqStats[binId] = binStats.sequenceStats(options.out_folder, f)
  File "/usr/local/lib/python2.7/site-packages/checkm/binStatistics.py", line 288, in sequenceStats
    seqStats[seqId]['Coding bases'] = seqStats[seqId].get('Coding bases', 0) + len(gene) * 3
UnboundLocalError: local variable 'gene' referenced before assignment

```
The coverage file has been obtained with checkm function "coverage" and none of the bin files are empty or have a strange name.

Could you please help troubleshooting here?
Thank you very much,

**Comment by dparks1134** [comment]
Missed issue. No critical issue with plot so am closing this ticket.
