### ISSUE TITLE
Keyerror while running bin_qa_plot

### ISSUE THREAD

**Issue by kumara3** [Ecogenomics/CheckM#230]
Hello,

I installed checkm using anaconda .
While running the bin_qa_plot I am getting the below error:
checkm bin_qa_plot . bins/bin.1/ out

[2019-10-24 11:32:16] INFO: CheckM v1.0.18
[2019-10-24 11:32:16] INFO: checkm bin_qa_plot . bins/bin.1/ out
[2019-10-24 11:32:16] INFO: [CheckM - bin_qa_plot] Creating bar plot of bin quality.
[2019-10-24 11:32:16] INFO: Calculating AAI between multi-copy marker genes.

**Unexpected error: <type 'exceptions.KeyError'>**
Traceback (most recent call last):
  File "/home1/06599/sanyasi/miniconda2/bin/checkm", line 714, in <module>
    checkmParser.parseOptions(args)
  File "/home1/06599/sanyasi/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 1177, in parseOptions
    self.binQAPlot(options)
  File "/home1/06599/sanyasi/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 788, in binQAPlot
    bMakePlot = plot.plot(binFiles, binStatsExt, options.bIgnoreHetero, aai.aaiHetero)
  File "/home1/06599/sanyasi/miniconda2/lib/python2.7/site-packages/checkm/plot/binQAPlot.py", line 72, in plot
    sortedBinIds = self.__sortBinsByCompleteness(binFiles, binStatsExt)
  File "/home1/06599/sanyasi/miniconda2/lib/python2.7/site-packages/checkm/plot/binQAPlot.py", line 45, in __sortBinsByCompleteness
    **sortedBinIds.append([binId, binStatsExt[binId]['Completeness']])
KeyError: 'genes'**

Please help.
Regards,
Ashwani

**Comment by dparks1134** [comment]
Missed issue. No follow-up so am assuming issue has been resolved or deemed not critical.
