### ISSUE TITLE
TypeError: exceptions must be old-style classes

### ISSUE THREAD

**Issue by iquasere** [Ecogenomics/CheckM#232]
Greetings

I have tried using the docker version of CheckM, but have encountered a TypeError. My input command was
```
docker run -v /path/to/bins_folder/:/bins_folder -v /checkm_output/:/checkm_output -it quay.io/biocontainers/checkm-genome:1.0.18--py_0 checkm lineage_wf -x fasta /bins_folder /checkm_output
```
I get the error message
```
Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 714, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 1138, in parseOptions
    self.tree(options)
  File "/usr/local/lib/python2.7/site-packages/checkm/main.py", line 156, in tree
    os.path.join(options.output_dir, 'storage', 'tree')
  File "/usr/local/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 105, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/usr/local/lib/python2.7/site-packages/checkm/resultsParser.py", line 85, in parseBinHits
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```
Is this a known bug? Or have I specified the input incorrectly?

**Comment by dparks1134** [comment]
Hi. This is a bug in the error reporting which does indicate there is something wrong with your input command or data.

**Comment by iquasere** [comment]
Just to follow up on those that might encounter this problem, I did manage to put check_m to work without need of different environments/python versions by using the [CheckM distribution](https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_2015_01_16.tar.gz) available at Ace Web Services.
```
curl -L -O curl -L -O https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_2015_01_16.tar.gz
tar xzf checkm_data_2015_01_16.tar.gz 
checkm data setRoot .
checkm lineage_wf -x fasta -r --ali --nt -t 14 --pplacer_threads 14 /mnt/HDDStorage/jsequeira/MOSCAfinal/Binning/Sample/ /mnt/HDDStorage/jsequeira/MOSCAfinal/Binning/Sample/quality_control
```
Even though this version is from 2015, it seems to work fine. Only solution I have found to work on my system.
