### ISSUE TITLE
Same error as before despite best efforts!

### ISSUE THREAD

**Issue by nixon444** [Ecogenomics/CheckM#235]
Sorry to raise the same issue as before but I simply cannot install your software on my Mac / servers. I hit a wall _every single time_ I try to install it elsewhere. I have it successfully installed in only one place, but I need to install on my local computer.

I followed your instructions, installed using pip, set root to where I downloaded and decompressed files. I ensured dependencies are in my system path. I have check the files against those I have on my one server where checkm works, and everything looks fine.

BUT I get this error (this with the test run 'checkm test ~/checkm_test_results' but the same error occurs with my own data):

$ checkm test ~/checkm_test_results
[2019-11-15 18:14:28] INFO: CheckM v1.0.18
[2019-11-15 18:14:28] INFO: checkm test /Users/user/checkm_test_results
[2019-11-15 18:14:28] INFO: [CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
[2019-11-15 18:14:28] INFO: [Step 1]: Verifying tree command.
[2019-11-15 18:14:28] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2019-11-15 18:14:28] INFO: Identifying marker genes in 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2019-11-15 18:14:42] INFO: Saving HMM info to file.
[2019-11-15 18:14:42] INFO: Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2019-11-15 18:14:42] INFO: Extracting marker genes to align.
[2019-11-15 18:14:42] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
[2019-11-15 18:14:42] INFO: Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
[2019-11-15 18:14:43] INFO: Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.
[2019-11-15 18:14:44] INFO: Reading marker alignment files.
[2019-11-15 18:14:44] INFO: Concatenating alignments.
[2019-11-15 18:14:44] INFO: Placing 1 bins into the genome tree with pplacer (be patient).
dyld: Library not loaded: /usr/local/lib/libgsl.0.dylib
  Referenced from: /Applications/pplacer-Darwin-v1.1/pplacer
  Reason: image not found
sh: line 1: 96590 Abort trap: 6           pplacer -j 1 -c /Users/user/checkmdata/genome_tree/genome_tree_reduced.refpkg -o /Users/user/checkm_test_results/results/storage/tree/concatenated.pplacer.json /Users/user/checkm_test_results/results/storage/tree/concatenated.fasta > /Users/user/checkm_test_results/results/storage/tree/pplacer.out
dyld: Library not loaded: /usr/local/lib/libgsl.0.dylib
  Referenced from: /Applications/pplacer-Darwin-v1.1/guppy
  Reason: image not found
[2019-11-15 18:14:44] INFO: { Current stage: 0:00:16.095 || Total: 0:00:16.095 }
[2019-11-15 18:14:44] INFO: [Passed]
[2019-11-15 18:14:44] INFO: [Step 2]: Verifying tree_qa command.
[2019-11-15 18:14:44] INFO: [CheckM - tree_qa] Assessing phylogenetic markers found in each bin.
[2019-11-15 18:14:44] INFO: Reading HMM info from file.
[2019-11-15 18:14:44] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

Unexpected error: <type 'exceptions.IOError'>
Traceback (most recent call last):
  File "/Users/user/opt/miniconda2/bin/checkm", line 714, in <module>
    checkmParser.parseOptions(args)
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 1205, in parseOptions
    self.test(options)
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 1099, in test
    verifyEcoli.run(self, options.output_dir)
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/checkm/test/test_ecoli.py", line 75, in run
    parser.treeQA(options)
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/checkm/main.py", line 186, in treeQA
    treeParser.printSummary(options.out_format, options.tree_dir, RP, options.bTabTable, options.file, binStats)
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/checkm/treeParser.py", line 45, in printSummary
    self.reportBinTaxonomy(outDir, resultsParser, bTabTable, outFile, binStats, bLineageStatistics=False)
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/checkm/treeParser.py", line 639, in reportBinTaxonomy
    binIdToTaxonomy = self.getBinTaxonomy(outDir, binIds)
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/checkm/treeParser.py", line 191, in getBinTaxonomy
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
  File "/Users/user/opt/miniconda2/lib/python2.7/site-packages/dendropy/utility/filesys.py", line 61, in pre_py34_open
    buffering=buffering)
IOError: [Errno 2] No such file or directory: '/Users/user/checkm_test_results/results/storage/tree/concatenated.tre'

Any ideas? Last time it was because I hadn't downloaded the files. This time I am certain I did everything correctly yet it still isn't playing ball...

**Comment by nixon444** [comment]
(ok so I also installed vua conda first, and looking again at the above it cannot unsee the conda installation though I uninstalled it...

I also got the same issue when I installed in a conda environment with the instructions you link to)

**Comment by dparks1134** [comment]
Hi nixon. Sorry for the very late reply. I hope you managed to resolve the issue. Unfortunately, I don't have any specific advice. From the error message it would appear the required CheckM reference data is missing.

**Comment by johnne** [comment]
Hi @nixon444 and @dparks1134,
I recently ran into this issue as well. I haven't used checkm in a few months and this was the first time I was testing it on my Mac from a Docker container running Linux. I'm fairly certain that this is a memory issue and that checkm fails because `pplacer` runs out of memory. That is why you see the error message about:

> IOError: [Errno 2] No such file or directory: '/Users/user/checkm_test_results/results/storage/tree/concatenated.tre

Have you tried running the `taxonomy_wf` on the test data? This doesn't use pplacer so that might give you an indication.

**Comment by dparks1134** [comment]
Closing as inactive for >2 weeks.
