### ISSUE TITLE
Errors after upgrading to python3

### ISSUE THREAD

**Issue by MrOlm** [Ecogenomics/CheckM#245]
Hi Donovan- thanks for releasing the python3 version of checkM! I'm trying to update dRep to account for checkM now being in python3, but am having trouble making the new checkM version work on my computer.

Installation went smoothly, but am hitting the following error when running it:

```
mattolm@Matts-MacBook-Pro-3:~/Programs/drep/tests$ checkm lineage_wf genomes/ test_backend/testchk
[2020-01-06 18:15:33] INFO: CheckM v1.1.2
[2020-01-06 18:15:33] INFO: checkm lineage_wf genomes/ test_backend/testchk
[2020-01-06 18:15:33] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2020-01-06 18:15:33] INFO: Identifying marker genes in 3 bins with 1 threads:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mattolm/.pyenv2/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/mattolm/.pyenv2/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mattolm/.pyenv2/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mattolm/.pyenv2/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__reportProgress'
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'
[2020-01-06 18:15:34] INFO: Saving HMM info to file.
[2020-01-06 18:15:34] INFO: Calculating genome statistics for 3 bins with 1 threads:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mattolm/.pyenv2/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mattolm/.pyenv2/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__processBin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mattolm/.pyenv2/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mattolm/.pyenv2/versions/3.8.0/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__reportProgress'
[2020-01-06 18:15:35] INFO: Extracting marker genes to align.
[2020-01-06 18:15:35] ERROR: Models must be parsed before identifying HMM hits.

  Controlled exit resulting from an unrecoverable error or warning.
```

When setting the root I hit some weird behavior, but I did download the database and put it there, so I don't think this is the problem:

```
mattolm@Matts-MacBook-Pro-3:~/Programs/drep/tests$ checkm data setRoot ~/.checkm2
[2020-01-06 18:14:23] INFO: CheckM v1.1.2
[2020-01-06 18:14:23] INFO: checkm data setRoot /Users/mattolm/.checkm2
[2020-01-06 18:14:23] INFO: [CheckM - data] Check for database updates. [setRoot]

Path [/Users/mattolm/.checkm2] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).

Path [/Users/mattolm/.checkm2] exists and you have permission to write to this folder.
(re) creating manifest file (please be patient).
mattolm@Matts-MacBook-Pro-3:~/Programs/drep/tests$ checkm data update
[2020-01-06 18:14:45] INFO: CheckM v1.1.2
[2020-01-06 18:14:45] INFO: checkm data update
[2020-01-06 18:14:45] INFO: [CheckM - data] Check for database updates. [update]
[2020-01-06 18:14:45] ERROR: Path to the CheckM reference data must be specified.``` 

Any idea what the problem might be?

Best,
Matt

**Comment by dparks1134** [comment]
Hi Matt. Not too sure what to suggest. I tested everything with Python 3.6.2, but the errors don't suggest an issue with the exact Python 3 version. 

The second issue with "ERROR: Path to the ..." is just an erroneous error message. It can be ignored. I thought this was fixed in v1.1.2, but apparently not.

**Comment by dparks1134** [comment]
Actually, `checkm data update` isn't valid anymore. I've updated the CheckM wiki to reflect this.

**Comment by MrOlm** [comment]
Hi Donovan,

I installed checkm in python 3.6.9 and it is working now- thanks for your quick response and help.

-Matt
