### ISSUE TITLE
checkM errors during checkM test

### ISSUE THREAD

**Issue by ialarmedalien** [Ecogenomics/CheckM#248]
- checkM installed through `pip3 install checkm-genome`
- reference data downloaded to `/data/checkm_data`, decompressed, and `checkm data setRoot /data/checkm_data` run.

Running `checkm test ~/checkm_test_results` gives the following output:

```
[2020-03-20 15:02:10] INFO: CheckM v1.1.2
[2020-03-20 15:02:10] INFO: checkm test /root/checkm_test_results
[2020-03-20 15:02:10] INFO: [CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
[2020-03-20 15:02:10] INFO: [Step 1]: Verifying tree command.
[2020-03-20 15:02:10] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2020-03-20 15:02:10] INFO: Identifying marker genes in 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2020-03-20 15:02:24] INFO: Saving HMM info to file.
[2020-03-20 15:02:24] INFO: Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2020-03-20 15:02:25] INFO: Extracting marker genes to align.
[2020-03-20 15:02:25] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
[2020-03-20 15:02:25] INFO: Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
[2020-03-20 15:02:25] INFO: Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.
[2020-03-20 15:02:26] INFO: Reading marker alignment files.
[2020-03-20 15:02:26] INFO: Concatenating alignments.
[2020-03-20 15:02:26] INFO: Placing 1 bins into the genome tree with pplacer (be patient).
Killed
Uncaught exception: Sys_error("/root/checkm_test_results/results/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("/root/checkm_test_results/results/storage/tree/concatenated.pplacer.json: No such file or directory")
[2020-03-20 15:02:59] INFO: { Current stage: 0:00:49.119 || Total: 0:00:49.119 }
[2020-03-20 15:02:59] INFO: [Passed]
[2020-03-20 15:02:59] INFO: [Step 2]: Verifying tree_qa command.
[2020-03-20 15:02:59] INFO: [CheckM - tree_qa] Assessing phylogenetic markers found in each bin.
[2020-03-20 15:02:59] INFO: Reading HMM info from file.
[2020-03-20 15:02:59] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/miniconda/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/miniconda/lib/python3.6/site-packages/checkm/main.py", line 909, in parseOptions
    self.test(options)
  File "/miniconda/lib/python3.6/site-packages/checkm/main.py", line 820, in test
    verifyEcoli.run(self, options.output_dir)
  File "/miniconda/lib/python3.6/site-packages/checkm/test/test_ecoli.py", line 75, in run
    parser.treeQA(options)
  File "/miniconda/lib/python3.6/site-packages/checkm/main.py", line 179, in treeQA
    treeParser.printSummary(options.out_format, options.tree_dir, RP, options.bTabTable, options.file, binStats)
  File "/miniconda/lib/python3.6/site-packages/checkm/treeParser.py", line 45, in printSummary
    self.reportBinTaxonomy(outDir, resultsParser, bTabTable, outFile, binStats, bLineageStatistics=False)
  File "/miniconda/lib/python3.6/site-packages/checkm/treeParser.py", line 641, in reportBinTaxonomy
    binIdToTaxonomy = self.getBinTaxonomy(outDir, binIds)
  File "/miniconda/lib/python3.6/site-packages/checkm/treeParser.py", line 191, in getBinTaxonomy
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/miniconda/lib/python3.6/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/root/checkm_test_results/results/storage/tree/concatenated.tre'
```
Any ideas on what might be going wrong here?

**Comment by dparks1134** [comment]
Hi. It appears you are running out of memory. CheckM requires 40 GB of memory to run. See the following for more details on system requirements
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements
