### ISSUE TITLE
coverage file created but 'profile' option gave error

### ISSUE THREAD

**Issue by wufabai** [Ecogenomics/CheckM#258]
Hi Donovan,

I have two questions:

1. I used the coverage option to create a coverage file, as attached:
[hyb2_PE_coverage.tsv.zip](https://github.com/Ecogenomics/CheckM/files/4519520/hyb2_PE_coverage.tsv.zip)
The file looks good. But then I want to use the profile option as follows:
checkm profile hyb2_PE_coverage.tsv;
or: 
checkm profile hyb2_PE_coverage.tsv -f hyb2_PE_coverage_profile.tsv
but both gave the following error:
_[2020-04-22 16:38:48] INFO: CheckM v1.1.1
[2020-04-22 16:38:48] INFO: checkm profile hyb2_PE_coverage.tsv -f hyb2_PE_coverage_profile.tsv
[2020-04-22 16:38:48] INFO: [CheckM - profile] Calculating percentage of reads mapped to each bin.
[2020-04-22 16:38:48] INFO: Determining number of reads mapped to each bin.
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python3.6/dist-packages/checkm/main.py", line 894, in parseOptions
    self.profile(options)
  File "/usr/local/lib/python3.6/dist-packages/checkm/main.py", line 673, in profile
    profile.run(options.coverage_file, options.file, options.bTabTable)
  File "/usr/local/lib/python3.6/dist-packages/checkm/profile.py", line 109, in run
    pTable = prettytable.PrettyTable(header)
NameError: name 'prettytable' is not defined_

Can you see where the issue come from?

2. It seems that the coverage option does not work with .bam files generated from single-end reads, is that correct? 

Thank you so much in advance,
Fabai

**Comment by dparks1134** [comment]
Hi Fabai. Sorry for the slow response. I am not sure what is causing issue 1. Prettytable is a 3rd party dependency, but the source file is included directly with CheckM. I have not had others report this issue so I would guess that it is an issue with the installation of CheckM on your system. Yes, CheckM only works with paired reads.
