### ISSUE TITLE
VERSION file missing 

### ISSUE THREAD

**Issue by aboffin** [Ecogenomics/CheckM#27]
Hi,

Installation fails since a VERSION file is absent in `checkm/` directory.

```
~/git_repos/CheckM $ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    version=version(),
  File "setup.py", line 8, in version
    versionFile = open(os.path.join(setupDir, 'checkm', 'VERSION'))
IOError: [Errno 2] No such file or directory: '/home/senthil/git_repos/CheckM/checkm/VERSION'
```

However, if I do this: `~/git_repos/CheckM $ echo "1.1" > checkm/VERSION`, the installation goes well:

```
~/git_repos/CheckM $ sudo python setup.py install
/usr/local/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/checkm
copying checkm/profile.py -> build/lib/checkm
copying checkm/defaultValues.py -> build/lib/checkm
copying checkm/markerSets.py -> build/lib/checkm
copying checkm/common.py -> build/lib/checkm
copying checkm/hmmerAligner.py -> build/lib/checkm
copying checkm/coverage.py -> build/lib/checkm
copying checkm/binUnion.py -> build/lib/checkm
copying checkm/binStatistics.py -> build/lib/checkm
copying checkm/genomicSignatures.py -> build/lib/checkm
copying checkm/resultsParser.py -> build/lib/checkm
copying checkm/taxonParser.py -> build/lib/checkm
copying checkm/main.py -> build/lib/checkm
copying checkm/unbinned.py -> build/lib/checkm
copying checkm/prettytable.py -> build/lib/checkm
copying checkm/binComparer.py -> build/lib/checkm
copying checkm/treeParser.py -> build/lib/checkm
copying checkm/markerGeneFinder.py -> build/lib/checkm
copying checkm/binTools.py -> build/lib/checkm
copying checkm/uniqueMarkers.py -> build/lib/checkm
copying checkm/coverageWindows.py -> build/lib/checkm
copying checkm/hmmerModelParser.py -> build/lib/checkm
copying checkm/pplacer.py -> build/lib/checkm
copying checkm/checkmData.py -> build/lib/checkm
copying checkm/PCA.py -> build/lib/checkm
copying checkm/merger.py -> build/lib/checkm
copying checkm/aminoAcidIdentity.py -> build/lib/checkm
copying checkm/__init__.py -> build/lib/checkm
copying checkm/timeKeeper.py -> build/lib/checkm
copying checkm/prodigal.py -> build/lib/checkm
copying checkm/ssuFinder.py -> build/lib/checkm
copying checkm/hmmer.py -> build/lib/checkm
creating build/lib/checkm/plot
copying checkm/plot/binQAPlot.py -> build/lib/checkm/plot
copying checkm/plot/cumulativeLengthPlot.py -> build/lib/checkm/plot
copying checkm/plot/tetraDistPlots.py -> build/lib/checkm/plot
copying checkm/plot/markerGenePosPlot.py -> build/lib/checkm/plot
copying checkm/plot/lengthHistogram.py -> build/lib/checkm/plot
copying checkm/plot/gcBiasPlots.py -> build/lib/checkm/plot
copying checkm/plot/gcPlots.py -> build/lib/checkm/plot
copying checkm/plot/distributionPlots.py -> build/lib/checkm/plot
copying checkm/plot/parallelCoordPlot.py -> build/lib/checkm/plot
copying checkm/plot/pcaPlot.py -> build/lib/checkm/plot
copying checkm/plot/codingDensityPlots.py -> build/lib/checkm/plot
copying checkm/plot/__init__.py -> build/lib/checkm/plot
copying checkm/plot/nxPlot.py -> build/lib/checkm/plot
copying checkm/plot/AbstractPlot.py -> build/lib/checkm/plot
creating build/lib/checkm/test
copying checkm/test/test_seqUtils.py -> build/lib/checkm/test
copying checkm/test/test_markerSets.py -> build/lib/checkm/test
copying checkm/test/test_ecoli.py -> build/lib/checkm/test
copying checkm/test/test_taxonomyUtils.py -> build/lib/checkm/test
copying checkm/test/test_aminoAcidIdentity.py -> build/lib/checkm/test
copying checkm/test/test_genomicSignatures.py -> build/lib/checkm/test
copying checkm/test/test_binStatistics.py -> build/lib/checkm/test
copying checkm/test/__init__.py -> build/lib/checkm/test
creating build/lib/checkm/util
copying checkm/util/img.py -> build/lib/checkm/util
copying checkm/util/taxonomyUtils.py -> build/lib/checkm/util
copying checkm/util/seqUtils.py -> build/lib/checkm/util
copying checkm/util/pfam.py -> build/lib/checkm/util
copying checkm/util/__init__.py -> build/lib/checkm/util
copying checkm/VERSION -> build/lib/checkm
copying checkm/DATA_CONFIG -> build/lib/checkm
running build_scripts
creating build/scripts-2.7
copying and adjusting bin/checkm -> build/scripts-2.7
changing mode of build/scripts-2.7/checkm from 644 to 755
running install_lib
creating /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/profile.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/defaultValues.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/markerSets.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/common.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/hmmerAligner.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/coverage.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/binUnion.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/binStatistics.py -> /usr/local/lib/python2.7/site-packages/checkm
creating /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/test/test_seqUtils.py -> /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/test/test_markerSets.py -> /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/test/test_ecoli.py -> /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/test/test_taxonomyUtils.py -> /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/test/test_aminoAcidIdentity.py -> /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/test/test_genomicSignatures.py -> /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/test/test_binStatistics.py -> /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/test/__init__.py -> /usr/local/lib/python2.7/site-packages/checkm/test
copying build/lib/checkm/genomicSignatures.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/resultsParser.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/taxonParser.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/main.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/unbinned.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/prettytable.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/binComparer.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/treeParser.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/DATA_CONFIG -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/markerGeneFinder.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/binTools.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/uniqueMarkers.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/coverageWindows.py -> /usr/local/lib/python2.7/site-packages/checkm
creating /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/binQAPlot.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/cumulativeLengthPlot.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/tetraDistPlots.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/markerGenePosPlot.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/lengthHistogram.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/gcBiasPlots.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/gcPlots.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/distributionPlots.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/parallelCoordPlot.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/pcaPlot.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/codingDensityPlots.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/__init__.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/nxPlot.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/plot/AbstractPlot.py -> /usr/local/lib/python2.7/site-packages/checkm/plot
copying build/lib/checkm/hmmerModelParser.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/VERSION -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/pplacer.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/checkmData.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/PCA.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/merger.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/aminoAcidIdentity.py -> /usr/local/lib/python2.7/site-packages/checkm
creating /usr/local/lib/python2.7/site-packages/checkm/util
copying build/lib/checkm/util/img.py -> /usr/local/lib/python2.7/site-packages/checkm/util
copying build/lib/checkm/util/taxonomyUtils.py -> /usr/local/lib/python2.7/site-packages/checkm/util
copying build/lib/checkm/util/seqUtils.py -> /usr/local/lib/python2.7/site-packages/checkm/util
copying build/lib/checkm/util/pfam.py -> /usr/local/lib/python2.7/site-packages/checkm/util
copying build/lib/checkm/util/__init__.py -> /usr/local/lib/python2.7/site-packages/checkm/util
copying build/lib/checkm/__init__.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/timeKeeper.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/prodigal.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/ssuFinder.py -> /usr/local/lib/python2.7/site-packages/checkm
copying build/lib/checkm/hmmer.py -> /usr/local/lib/python2.7/site-packages/checkm
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/profile.py to profile.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/defaultValues.py to defaultValues.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/markerSets.py to markerSets.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/common.py to common.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/hmmerAligner.py to hmmerAligner.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/coverage.py to coverage.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/binUnion.py to binUnion.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/binStatistics.py to binStatistics.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/test/test_seqUtils.py to test_seqUtils.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/test/test_markerSets.py to test_markerSets.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/test/test_ecoli.py to test_ecoli.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/test/test_taxonomyUtils.py to test_taxonomyUtils.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/test/test_aminoAcidIdentity.py to test_aminoAcidIdentity.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/test/test_genomicSignatures.py to test_genomicSignatures.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/test/test_binStatistics.py to test_binStatistics.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/test/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/genomicSignatures.py to genomicSignatures.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/resultsParser.py to resultsParser.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/taxonParser.py to taxonParser.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/main.py to main.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/unbinned.py to unbinned.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/prettytable.py to prettytable.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/binComparer.py to binComparer.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/treeParser.py to treeParser.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/markerGeneFinder.py to markerGeneFinder.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/binTools.py to binTools.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/uniqueMarkers.py to uniqueMarkers.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/coverageWindows.py to coverageWindows.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/binQAPlot.py to binQAPlot.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/cumulativeLengthPlot.py to cumulativeLengthPlot.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/tetraDistPlots.py to tetraDistPlots.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/markerGenePosPlot.py to markerGenePosPlot.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/lengthHistogram.py to lengthHistogram.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/gcBiasPlots.py to gcBiasPlots.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/gcPlots.py to gcPlots.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/distributionPlots.py to distributionPlots.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/parallelCoordPlot.py to parallelCoordPlot.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/pcaPlot.py to pcaPlot.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/codingDensityPlots.py to codingDensityPlots.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/nxPlot.py to nxPlot.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/plot/AbstractPlot.py to AbstractPlot.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/hmmerModelParser.py to hmmerModelParser.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/pplacer.py to pplacer.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/checkmData.py to checkmData.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/PCA.py to PCA.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/merger.py to merger.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/aminoAcidIdentity.py to aminoAcidIdentity.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/util/img.py to img.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/util/taxonomyUtils.py to taxonomyUtils.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/util/seqUtils.py to seqUtils.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/util/pfam.py to pfam.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/util/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/timeKeeper.py to timeKeeper.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/prodigal.py to prodigal.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/ssuFinder.py to ssuFinder.pyc
byte-compiling /usr/local/lib/python2.7/site-packages/checkm/hmmer.py to hmmer.pyc
running install_scripts
copying build/scripts-2.7/checkm -> /usr/local/bin
changing mode of /usr/local/bin/checkm to 755
running install_egg_info
Writing /usr/local/lib/python2.7/site-packages/checkm_genome-1.1-py2.7.egg-info
```

Sen

**Comment by dparks1134** [comment]
Hello Sen,

I have added the VERSION file to the repository along with customHelpFormatter.py. In general, I suggest installing CheckM through pip and/or using the latest official release (v0.9.7). CheckM is in active development so the latest code in the main branch is not always stable and may contain features that are not fully tested.

Cheers,
Donovan
