### ISSUE TITLE
FileNotFoundError on concatenated.tre

### ISSUE THREAD

**Issue by MatthewRalston** [Ecogenomics/CheckM#271]
Hello, I'm running into an issue while running checkm for the first time. I'm running `--reduced_tree` to test on limited resources, but I have several gigs of storage to write outputs to, I'm not sure why the tree file is not being generated.

```
(base) root@2bd161e4e4ce:/# checkm lineage_wf --reduced_tree -x fa checkm_in/ checkm_out                                                       [39/391]
[2020-07-27 21:26:54] INFO: CheckM v1.1.2
[2020-07-27 21:26:54] INFO: checkm lineage_wf --reduced_tree -x fa checkm_in/ checkm_out
[2020-07-27 21:26:54] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2020-07-27 21:26:54] INFO: Identifying marker genes in 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2020-07-27 21:27:15] INFO: Saving HMM info to file.
[2020-07-27 21:27:15] INFO: Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2020-07-27 21:27:16] INFO: Extracting marker genes to align.
[2020-07-27 21:27:16] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
[2020-07-27 21:27:16] INFO: Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
[2020-07-27 21:27:16] INFO: Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.
[2020-07-27 21:27:17] INFO: Reading marker alignment files.
[2020-07-27 21:27:17] INFO: Concatenating alignments.
[2020-07-27 21:27:17] INFO: Placing 1 bins into the genome tree with pplacer (be patient).
Killed
Uncaught exception: Sys_error("checkm_out/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("checkm_out/storage/tree/concatenated.pplacer.json: No such file or directory")
[2020-07-27 21:27:56] INFO: { Current stage: 0:01:01.970 || Total: 0:01:01.970 }
[2020-07-27 21:27:56] INFO: [CheckM - lineage_set] Inferring lineage-specific marker sets.
[2020-07-27 21:27:56] INFO: Reading HMM info from file.
[2020-07-27 21:27:56] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
[2020-07-27 21:27:56] INFO: Determining marker sets for each genome bin.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/opt/conda/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/opt/conda/lib/python3.7/site-packages/checkm/main.py", line 859, in parseOptions
    self.lineageSet(options)
  File "/opt/conda/lib/python3.7/site-packages/checkm/main.py", line 215, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/opt/conda/lib/python3.7/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/opt/conda/lib/python3.7/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'checkm_out/storage/tree/concatenated.tre'
```

**Comment by dparks1134** [comment]
It appears you are running our of RAM. I'm inferring this from the process being `Killed` when trying to place genomes into the reference tree. The reduced tree still requires ~16 GB.
