### ISSUE TITLE
ERROR: Models must be parsed before identifying HMM hits.

### ISSUE THREAD

**Issue by XMTian** [Ecogenomics/CheckM#280]
Hi,

When I run checkM, I got this error. I already saw the same error in previous issues. The solution (change doc to unix format) didn't work for me. Could you help me to figure out this error? 

`[2020-12-03 22:42:57] INFO: CheckM v1.1.3
[2020-12-03 22:42:57] INFO: checkm lineage_wf --reduced_tree -t 2 /Users/xmtian/PhD/01.MicroAssem/db/01.test /Users/xmtian/PhD/01.MicroAssem/db/01.test/checkm
[2020-12-03 22:42:57] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2020-12-03 22:42:57] INFO: Identifying marker genes in 2 bins with 2 threads:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__reportProgress'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'
[2020-12-03 22:42:59] INFO: Saving HMM info to file.
[2020-12-03 22:42:59] INFO: Calculating genome statistics for 2 bins with 2 threads:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__reportProgress'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__processBin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.0_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__processBin'
[2020-12-03 22:43:00] INFO: Extracting marker genes to align.
[2020-12-03 22:43:00] ERROR: Models must be parsed before identifying HMM hits.

  Controlled exit resulting from an unrecoverable error or warning.`

I have installed all software it depends on.
![image](https://user-images.githubusercontent.com/45260595/101092323-c5483e00-35b9-11eb-8822-dca6b5dba742.png)

Many thanks,
Xiaomeng

**Comment by dparks1134** [comment]
Hi. It appears to be something wrong with the installation, but I'm not sure what to suggest. You could try the CheckM Conda package or running CheckM via KBase: https://kbase.us/applist/apps/kb_Msuite/run_checkM_lineage_wf/release?gclid=Cj0KCQiAtqL-BRC0ARIsAF4K3WGEJpfdj0q_uHyJN251A2qPrE4O_MJHD7rdKDR01D4RnitsHJP4M3AaAsJdEALw_wcB.

**Comment by XMTian** [comment]
Hi, Thank you, KBase works.

**Comment by dparks1134** [comment]
Hi. This is a known issue when using MacOS and Python >=3.8. This has been fixed in the latest release of CheckM (v1.2.1) which is now available on PyPi. I don't maintain the BioConda install of CheckM, but hopefully this will be updated to v1.2.1 shortly.
