### ISSUE TITLE
checkm tmp file not found error

### ISSUE THREAD

**Issue by sapuizait** [Ecogenomics/CheckM#291]
Hi 
I have been running checkm on a slurm cluster and even though in the past I have successfully run it (ca. 4200 genomes/MAGs takes a bit more than 8hr), now I get some weird error.
For this job I have assigned 32 processors and 200G RAM

Here is the error:
[2021-04-05 11:32:47] INFO: { Current stage: 0:19:30.139 || Total: 9:48:27.352 }
[2021-04-05 11:32:47] INFO: [CheckM - analyze] Identifying marker genes in bins.
[2021-04-05 11:33:07] INFO: Identifying marker genes in 5721 bins with 32 threads:

Process SyncManager-134:
Traceback (most recent call last):
  File "/home/baboun/miniconda3/envs/dRep-env/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/baboun/miniconda3/envs/dRep-env/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/baboun/miniconda3/envs/dRep-env/lib/python3.6/multiprocessing/managers.py", line 539, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/home/baboun/miniconda3/envs/dRep-env/lib/python3.6/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/home/baboun/miniconda3/envs/dRep-env/lib/python3.6/multiprocessing/connection.py", line 432, in __init__
    address = address or arbitrary_address(family)
  File "/home/baboun/miniconda3/envs/dRep-env/lib/python3.6/multiprocessing/connection.py", line 76, in arbitrary_address
    return tempfile.mktemp(prefix='listener-', dir=util.get_temp_dir())
  File "/home/baboun/miniconda3/envs/dRep-env/lib/python3.6/multiprocessing/util.py", line 114, in get_temp_dir
    tempdir = tempfile.mkdtemp(prefix='pymp-')
  File "/home/baboun/miniconda3/envs/dRep-env/lib/python3.6/tempfile.py", line 370, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/storage/scratch/baboun/36493032//tmp/pymp-t8vd69bj'

Unexpected error: <class 'EOFError'>

----------------------------------------------------

any idea if it is RAM related or space related and if i should reduce the number of MAGs I analyze in parallel? for example 3-4k at a time?

thanks
P

**Comment by dparks1134** [comment]
I generally recommend running in batches of 1,000:
https://github.com/Ecogenomics/CheckM/wiki/Bugs-and-Feature-Requests#processing-large-numbers-of-genomes
