### ISSUE TITLE
checkmParser.parseOptions(args)

### ISSUE THREAD

**Issue by Ceseon** [Ecogenomics/CheckM#292]
Hi
I installed CheckM (latest version) via Conda and I create a environment only for this program using python=3.7, but I don't know what happen, every time that I attempt to run it prompts the same error.

I hope we can solve it.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/home/cesar/miniconda3/envs/checkmenv/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/home/cesar/miniconda3/envs/checkmenv/lib/python3.7/site-packages/checkm/main.py", line 859, in parseOptions
    self.lineageSet(options)
  File "/home/cesar/miniconda3/envs/checkmenv/lib/python3.7/site-packages/checkm/main.py", line 215, in lineageSet
    resultsParser, options.unique, options.multi)
  File "/home/cesar/miniconda3/envs/checkmenv/lib/python3.7/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/home/cesar/miniconda3/envs/checkmenv/lib/python3.7/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/cesar/Documentos/tesis_arch/checkm_result_2/storage/tree/concatenated.tre'

**Comment by Caiyulu-818** [comment]
hi. I meet the same error ,do you solve it ?

**Comment by dparks1134** [comment]
The Conda install of CheckM is community supported and was not put together by myself. Sorry I can't provide any direct assistance.
