### ISSUE TITLE
error while bin_refinement

### ISSUE THREAD

**Issue by Caiyulu-818** [Ecogenomics/CheckM#307]
error messgae:
Aligning marker genes with multiple hits in a single bin:
    Finished processing 0 of 4463 (0.00%) bins.
Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/data2/lcy/miniconda3/envs/metawrap-env/bin/checkm", line 708, in <module>
    checkmParser.parseOptions(args)
  File "/data2/lcy/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 1253, in parseOptions
    self.analyze(options)
  File "/data2/lcy/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/main.py", line 331, in analyze
    os.path.join(options.out_folder, 'storage', 'aai_qa')
  File "/data2/lcy/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 176, in makeAlignmentsOfMultipleHits
    p.terminate()
  File "/data2/lcy/miniconda3/envs/metawrap-env/lib/python2.7/multiprocessing/process.py", line 140, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'

is it too much genomes input that cause the error ?

**Comment by dparks1134** [comment]
Hi. The number of bins is acceptable assuming your machine has sufficient memory. I usually run genomes in batches of 1,000 just to ensure any issues (e.g., ill-formatted input data) do not result in the entire run failing. The problem does appear to be with CheckM, but perhaps this is a result of how the data is handle by metawrap prior to being executed. I'm not familiar enough with metawrap to know if this could be an issue.
