### ISSUE TITLE
checkm error 

### ISSUE THREAD

**Issue by Caiyulu-818** [Ecogenomics/CheckM#311]
[2021-08-03 21:24:26] INFO: CheckM v1.1.3
[2021-08-03 21:24:26] INFO: checkm lineage_wf -t 24 -x fna --tab_table -f checkm1_qa.txt /BIGDATA2/zju_bma_1/reference/patric/checkm/checkm1-3549 /BIGDATA2/zju_bma_1/reference/patric/checkmresult/qcheckm1
[2021-08-03 21:24:26] INFO: [CheckM - tree] Placing bins in reference genome tree.

Unexpected error: <class 'ZeroDivisionError'>
Traceback (most recent call last):
  File "/BIGDATA2/zju_bma_1/.conda/envs/checkm/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/BIGDATA2/zju_bma_1/.conda/envs/checkm/lib/python3.6/site-packages/checkm/main.py", line 858, in parseOptions
    self.tree(options)
  File "/BIGDATA2/zju_bma_1/.conda/envs/checkm/lib/python3.6/site-packages/checkm/main.py", line 107, in tree
    if not checkNuclotideSeqs(binFiles):
  File "/BIGDATA2/zju_bma_1/.conda/envs/checkm/lib/python3.6/site-packages/checkm/util/seqUtils.py", line 142, in checkNuclotideSeqs
    if not isNucleotide(seq_file):
  File "/BIGDATA2/zju_bma_1/.conda/envs/checkm/lib/python3.6/site-packages/checkm/util/seqUtils.py", line 72, in isNucleotide
    if float(nt_bases) / len(seq) >= req_perc:
ZeroDivisionError: float division by zero

 hello I meet a new error, can you help me to know which module has problem ? 
thanks a lot

**Comment by dparks1134** [comment]
The error suggest you have a sequence of zero length. Can you verify your input data is correct?

**Comment by Caiyulu-818** [comment]
> The error suggest you have a sequence of zero length. Can you verify your input data is correct?
 my input data is not empty, the file input include many .fna files

**Comment by dparks1134** [comment]
Are there sequences in your input *.fna files that have zero length? The error suggest this is the case.

**Comment by Caiyulu-818** [comment]
> The
no there is no fan files with zero length, and  I try  it again for other files, it  always has this problem

**Comment by Caiyulu-818** [comment]
and I try a small file with 5-10 files it works and finished the checkm but for the file with 1500 files it didn't work with this error.

**Comment by dparks1134** [comment]
Hi. It is likely an issue with one of your input files. Unfortunately, I'm not sure what the easiest way to confirm this would be.

**Comment by Caiyulu-818** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Yes. I agree withy you, it maybe error because one of the files, thank you so much !
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                lucyncs123
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 08/17/2021 21:58，Donovan ***@***.***> wrote： 



Hi. It is likely an issue with one of your input files. Unfortunately, I'm not sure what the easiest way to confirm this would be.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
