### ISSUE TITLE
checkm setRoot not working

### ISSUE THREAD

**Issue by dzolier** [Ecogenomics/CheckM#319]
Hello,

I am using checkm as part of a data pipeline in nextflow (called MUFFIN) and checkm data setRoot does not seem to set the location properly.

Thus far, I've tried `checkm data setRoot /path/to/checkm/db` as a super user and normally (which was in a previous issue), I've interrupted `checkm data setRoot /path/to/checkm/db` and re-run it (which I read in an older bug report), and I have copied the .dmanifest file to every single home folder in the pipeline and used the `-resume` feature (which wouldn't work anyways because nextflow creates new folders for `-resume`). 

In every case, CheckM assumes it has never been used and proceeds to run the `checkm data setRoot` process anyways, which causes an EOF error in nextflow. The result is as follows:

```
[skipping] Stored process > sourmash_download_db
[skipping] Stored process > checkm_download_db
Error executing process > 'refine2 (1)'

Caused by:
  Process `refine2 (1)` terminated with an error exit status (1)

Command executed:

  mem=$(echo 490 GB | sed 's/g//g')
  path_db=$(cat path_db.txt)
  echo $path_db
  checkm data setRoot $path_db
  echo "checkm done"
  metawrap bin_refinement -o refined_bins -A bins_dir -B fasta_bins -o refined_bins -t 120 -m $mem
  mkdir metawrap_bins/
  mv refined_bins/metawrap_70_10_bins/*.fa metawrap_bins/
  mv refined_bins/metawrap_70_10_bins.stats subset_binning_stats.txt

Command exit status:
  1

Command output:
  /home/ubuntu/nextflow-autodownload-databases/checkm/db
  It seems that the CheckM data folder has not been set yet or has been removed. Running: 'checkm data setRoot'.
  Where should CheckM store it's data?
  Please specify a location or type 'abort' to stop trying:

Command error:
  Traceback (most recent call last):
    File "/home/ubuntu/work/conda/env-365fdf3d23c18ec576559d837f2bcac1/bin/checkm", line 36, in <module>
      from checkm import main
    File "/home/ubuntu/work/conda/env-365fdf3d23c18ec576559d837f2bcac1/lib/python2.7/site-packages/checkm/main.py", line 25, in <module>
      from checkm.defaultValues import DefaultValues
    File "/home/ubuntu/work/conda/env-365fdf3d23c18ec576559d837f2bcac1/lib/python2.7/site-packages/checkm/defaultValues.py", line 26, in <module>
      class DefaultValues():
    File "/home/ubuntu/work/conda/env-365fdf3d23c18ec576559d837f2bcac1/lib/python2.7/site-packages/checkm/defaultValues.py", line 29, in DefaultValues
      __DBM = DBManager()
    File "/home/ubuntu/work/conda/env-365fdf3d23c18ec576559d837f2bcac1/lib/python2.7/site-packages/checkm/checkmData.py", line 114, in __init__
      if not self.setRoot():
    File "/home/ubuntu/work/conda/env-365fdf3d23c18ec576559d837f2bcac1/lib/python2.7/site-packages/checkm/checkmData.py", line 140, in setRoot
      path = self.confirmPath(path=path)
    File "/home/ubuntu/work/conda/env-365fdf3d23c18ec576559d837f2bcac1/lib/python2.7/site-packages/checkm/checkmData.py", line 162, in confirmPath
      path = raw_input("Where should CheckM store it's data?\n" \
  EOFError: EOF when reading a line

Work dir:
  /home/ubuntu/work/77/45259df79f2c8ef7bc92cd48e3b81a

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.

```
Any advice you can provide is much appreciated.

**Comment by dzolier** [comment]
I figured out a solution.

My solution was to editthe DATA_CONFIG file located at `/.../site-packages/checkm/DATA_CONFIG`

I replaced the entry corresponding to '"dataRoot"' to `"path/to/checkm/db"` and it worked just fine afterwards -- so I'd assume that's the manual equivalent of using `checkm data setRoot path/to/checkm/db`
