### ISSUE TITLE
 AttributeError: 'Namespace' object has no attribute 'bCalledGenes'

### ISSUE THREAD

**Issue by neelam19051** [Ecogenomics/CheckM#332]
Hi I am trying to make plot by using checkm output and the error is given below-
Please help me if anyone know anything about it.

****checkm gc_plot ./bins ./plots 95**

CheckM v1.1.9
[2022-04-21 17:12:06] INFO: checkm gc_plot ./bins ./plots 95
[2022-04-21 17:12:06] INFO: CheckM data: /home/bvs/anaconda3/envs/myenv/checkm_data
[2022-04-21 17:12:06] INFO: [CheckM - gc_plot] Creating GC histogram and delta-GC plot.

Unexpected error: <class 'AttributeError'>
Traceback (most recent call last):
  File "/home/bvs/anaconda3/envs/myenv/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.9/site-packages/checkm/main.py", line 996, in parseOptions
    self.gcPlot(options)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.9/site-packages/checkm/main.py", line 471, in gcPlot
    checkBinInputExists(options.bin_input, options.bCalledGenes)
**AttributeError: 'Namespace' object has no attribute 'bCalledGenes'**

Thank you

**Comment by dparks1134** [comment]
Hi. Thanks for pointing this out. The issue has been fixed in v1.1.10.

**Comment by neelam19051** [comment]
Hi, could you please share checkm plot script in detail because even after updating still i am unable to plot. I am very grateful to you.

**Comment by neelam19051** [comment]
Hi, could you please tell me where i am wrong ?

**checkm gc_plot ./bins ./plots 90**
[2022-04-22 11:07:52] INFO: CheckM v1.1.10
[2022-04-22 11:07:52] INFO: checkm gc_plot ./bins ./plots 90
[2022-04-22 11:07:52] INFO: CheckM data: /home/bvs/.checkm
[2022-04-22 11:07:52] INFO: [CheckM - gc_plot] Creating GC histogram and delta-GC plot.
[2022-04-22 11:07:52] **ERROR: No bins found. Check the extension (-x) used to identify bins.**

  Controlled exit resulting from an unrecoverable error or warning.


Thank you!

**Comment by dparks1134** [comment]
Hi,

If the FASTA files in your `bins` directory don't end in `.fna` you need to set the correct extension with the `-x` flag, e.g.:
```
> checkm gc_plot ./bins ./plots 90 -x .fa
```

**Comment by neelam19051** [comment]
Hi, Thank you for your reply but still i am unable to plot even after providing fna file. Can check it again please.

checkm gc_plot   /home/bvs/neelam/genome/fna_p ./plots 95
[2022-04-22 21:43:47] INFO: CheckM v1.1.10
[2022-04-22 21:43:47] INFO: checkm gc_plot /home/bvs/neelam/genome/fna_p ./plots 95
[2022-04-22 21:43:47] INFO: CheckM data: /home/bvs/.checkm
[2022-04-22 21:43:47] INFO: [CheckM - gc_plot] Creating GC histogram and delta-GC plot.
[2022-04-22 21:43:47] INFO: Plotting GC plots for /home/bvs/neelam/genome/fna_p/P_aeruginosa_1.fna (1 of 359)
[2022-04-22 21:43:47] ERROR: Input file does not exists: /home/bvs/.checkm/distributions/gc_dist.txt


  Controlled exit resulting from an unrecoverable error or warning.


Thank you

**Comment by dparks1134** [comment]
Hi,

This is an installation issue. CheckM has reference data it needs to be able to locate:
https://github.com/Ecogenomics/CheckM/wiki/Installation#required-reference-data

Cheers,
Donovan

**Comment by neelam19051** [comment]
> 

Thank you so much for your help ..Now it solve.

**Comment by neelam19051** [comment]
Hi, i am getting this error during marker plot, if possible please have a look.
**checkm marker_plot ./output /home/bvs/neelam/genome/fna_p ./plots_6**
[2022-04-24 17:40:30] INFO: CheckM v1.1.10
[2022-04-24 17:40:30] INFO: checkm marker_plot ./output /home/bvs/neelam/genome/fna_p ./plots_6

Thank you!
[2022-04-24 17:40:30] INFO: CheckM data: /home/bvs/neelam/checkm_data
[2022-04-24 17:40:30] INFO: [CheckM - marker_plot] Creating marker gene position plot.
[2022-04-24 17:40:38] INFO: Plotting marker gene position plot for P_aeruginosa_1 (1 of 359)
[2022-04-24 17:40:38] INFO: Markers reside on 1 of 2 sequences which span 7.21 of 7.23 (99.7%) Mb

Unexpected error: <class 'AttributeError'>
Traceback (most recent call last):
  File "/home/bvs/anaconda3/envs/myenv/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.9/site-packages/checkm/main.py", line 1009, in parseOptions
    self.markerPlot(options)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.9/site-packages/checkm/main.py", line 702, in markerPlot
    bPlotted = plot.plot(f, markerGeneStats[binId], binStats[binId])
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.9/site-packages/checkm/plot/markerGenePosPlot.py", line 112, in plot
    yLabelBounds = self.yLabelExtents(yLabels, self.options.font_size)
  File "/home/bvs/anaconda3/envs/myenv/lib/python3.9/site-packages/checkm/plot/AbstractPlot.py", line 124, in yLabelExtents
    bboxi = bbox.inverse_transformed(self.fig.transFigure)
AttributeError: 'Bbox' object has no attribute 'inverse_transformed'

**Comment by dparks1134** [comment]
Hi. This should be fixed in v1.1.11. Thanks.

**Comment by neelam19051** [comment]
Hi, thank you so much, now it's working perfectly fine. could you please tell me how to make single plot for all large genome, however it plot single plot for single genome.


Thank you

**Comment by dparks1134** [comment]
Hi. The marker_plot creates a single row per genome. It doesn't have the capability of producing any other style of plot.
