### ISSUE TITLE
IndexError: Indez out of range when trying to perform a QC on a single bin

### ISSUE THREAD

**Issue by reymonera** [Ecogenomics/CheckM#346]
Hi!

After executing `$ checkm lineage_wf -t 4 -x fa bins.1.fa checkm/` I'm encountering this error:

```
[2022-07-14 00:46:22] INFO: CheckM v1.2.0
[2022-07-14 00:46:22] INFO: checkm lineage_wf -t 4 -x fa bins.1.fa checkm/
[2022-07-14 00:46:22] INFO: CheckM data: /home/ccastillo/checkm_db
[2022-07-14 00:46:22] INFO: [CheckM - tree] Placing bins in reference genome tree.

Unexpected error: <class 'IndexError'>
Traceback (most recent call last):
  File "/home/ccastillo/.conda/envs/checkm/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/ccastillo/.conda/envs/checkm/lib/python3.7/site-packages/checkm/main.py", line 979, in parseOptions
    self.tree(options)
  File "/home/ccastillo/.conda/envs/checkm/lib/python3.7/site-packages/checkm/main.py", line 142, in tree
    options.bin_input, options.extension, options.bCalledGenes)
  File "/home/ccastillo/.conda/envs/checkm/lib/python3.7/site-packages/checkm/main.py", line 106, in binFiles
    binFile = files[1]
IndexError: list index out of range
```
I installed CheckM using conda, and apparently all the libraries required are installed. Is there any type of specific error I should check about?

Thanks for any help you could give me!

Regards,

**Comment by dparks1134** [comment]
Hi. Sorry for the slow reply. Is this still an outstanding issue? I believe the issue is that CheckM expects a directory of genomic FASTA files and not a single FASTA file as the first parameter.

**Comment by cedwardson4** [comment]
I just had this issue as well. Giving CheckM a directory rather than a single FASTA file solved it!
