### ISSUE TITLE
AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'

### ISSUE THREAD

**Issue by rachelmugge** [Ecogenomics/CheckM#347]
Hello,
I am attempting to run CheckM after a successful install, but when I ran this command:

`checkm lineage_wf -t 1 -x .fa --reduced_tree /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_3_assemblybased/09_das_tool/output/B001_DASTool_bins /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_Microcosm2.0/pipeline_3_assemblybased/10_checkM`

It produced these errors:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'MarkerGeneFinder' object has no attribute '__reportProgress'
[2022-08-02 18:24:35] INFO: Saving HMM info to file.
[2022-08-02 18:24:35] INFO: Calculating genome statistics for 4 bins with 1 threads:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__reportProgress'
    self = reduction.pickle.load(from_parent)
AttributeError: 'BinStatistics' object has no attribute '__processBin'
[2022-08-02 18:24:37] INFO: Extracting marker genes to align.
[2022-08-02 18:24:37] ERROR: Models must be parsed before identifying HMM hits.

  Controlled exit resulting from an unrecoverable error or warning.

I assume there are multiple errors because they build on each other, but I could not find a solution to the first error: 

`AttributeError: 'MarkerGeneFinder' object has no attribute '__processBin'`

Not sure if this is an installation or an input issue.

Relevant info:
CheckM version: 1.2.0
Python version: 3.9.13
Installation method: pip3
MacOS: Monterey (12.1)
Input # bins: 4
Input # threads: 1
Data directory has been set

Any suggestions are welcome- thanks!

**Comment by dparks1134** [comment]
Hi. This is a known issue when using MacOS and Python >=3.8. This has been fixed in the latest release of CheckM (v1.2.1) which is now available on PyPi. I don't maintain the BioConda install of CheckM, but hopefully this will be updated to v1.2.1 shortly.

**Comment by rachelmugge** [comment]
Thanks for the speedy reply!

I uninstalled CheckM v1.2.0 and installed v1.2.1 both via pip, and unfortunately it still kicked back the same errors. I will have to do some more troubleshooting, and/or try running the newest version of CheckM with a slightly older version of python3 and see what happens.

**Comment by dparks1134** [comment]
Closed due to inactivity.
