### ISSUE TITLE
ERROR: Models must be parsed before identifying HMM hits

### ISSUE THREAD

**Issue by sapuizait** [Ecogenomics/CheckM#353]
checkm suddenly stopped working...

I get the following error:

[2022-10-06 19:18:59] INFO: CheckM v1.2.1
[2022-10-06 19:18:59] INFO: checkm lineage_wf -t 8 -x fas newf/ out/
[2022-10-06 19:18:59] INFO: CheckM data: /home/pasapoun/data/input/draft
[2022-10-06 19:18:59] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2022-10-06 19:18:59] INFO: Identifying marker genes in 1 bins with 8 threads:
Process Process-2:ssing 0 of 1 (0.00%) bins.
Traceback (most recent call last):
  File "/home/pasapoun/miniconda3/envs/dRep-env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/pasapoun/miniconda3/envs/dRep-env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pasapoun/miniconda3/envs/dRep-env/lib/python3.8/site-packages/checkm/markerGeneFinder.py", line 122, in _processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/home/pasapoun/miniconda3/envs/dRep-env/lib/python3.8/site-packages/checkm/markerSets.py", line 330, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/home/pasapoun/miniconda3/envs/dRep-env/lib/python3.8/site-packages/checkm/markerSets.py", line 430, in markerFileType
    with open(markerFile, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pasapoun/data/input/draft/hmms/phylo.hmm'

[2022-10-06 19:19:00] INFO: Saving HMM info to file.
[2022-10-06 19:19:00] INFO: Calculating genome statistics for 1 bins with 8 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2022-10-06 19:19:00] INFO: Extracting marker genes to align.
[2022-10-06 19:19:00] ERROR: Models must be parsed before identifying HMM hits.

  Controlled exit resulting from an unrecoverable error or warning.

I m trying to run it on a slurm server using a bioconda installation. 
Any ideas?

**Comment by sapuizait** [comment]
apologies, pure stupidity, i had accidentally deleted the db... :(
