### ISSUE TITLE
Uncaught exception: Multiprocessing.Child_error

### ISSUE THREAD

**Issue by zoubohao** [Ecogenomics/CheckM#357]
When I was running checkm with the following command: checkm lineage, it raised up error:

[2022-11-15 11:33:51] INFO: CheckM v1.2.1
[2022-11-15 11:33:51] INFO: checkm lineage_wf -t 25 --pplacer_threads 25 -x fasta -f ../AllData/RealDataBinningModels/MaxBin_Data/HLJ/DeepurifyTempOut/FilterOutput/family_checkm.txt --reduced_tree ../AllData/RealDataBinningModels/MaxBin_Data/HLJ/DeepurifyTempOut/FilterOutput/family_filter ../AllData/RealDataBinningModels/MaxBin_Data/HLJ/DeepurifyTempOut/FilterOutput/family_filter/checkmTempOut
[2022-11-15 11:33:51] INFO: CheckM data: /home/zoubh/Softwares/checkm_database/
[2022-11-15 11:33:51] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2022-11-15 11:33:54] INFO: Identifying marker genes in 831 bins with 25 threads:
    Finished processing 831 of 831 (100.00%) bins.
[2022-11-15 11:34:06] INFO: Saving HMM info to file.
[2022-11-15 11:34:06] INFO: Calculating genome statistics for 831 bins with 25 threads:
    Finished processing 831 of 831 (100.00%) bins.
[2022-11-15 11:34:08] INFO: Extracting marker genes to align.
[2022-11-15 11:34:08] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 831 of 831 (100.00%) bins.
[2022-11-15 11:34:34] INFO: Extracting 43 HMMs with 25 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
[2022-11-15 11:34:34] INFO: Aligning 43 marker genes with 25 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.
[2022-11-15 11:34:36] INFO: Reading marker alignment files.
[2022-11-15 11:34:36] INFO: Concatenating alignments.
[2022-11-15 11:34:36] INFO: Placing 831 bins into the genome tree with pplacer (be patient).
Uncaught exception: Multiprocessing.Child_error(_)
Fatal error: exception Multiprocessing.Child_error(_)
Uncaught exception: Sys_error("../AllData/RealDataBinningModels/MaxBin_Data/HLJ/DeepurifyTempOut/FilterOutput/family_filter/checkmTempOut/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("../AllData/RealDataBinningModels/MaxBin_Data/HLJ/DeepurifyTempOut/FilterOutput/family_filter/checkmTempOut/storage/tree/concatenated.pplacer.json: No such file or directory")
[2022-11-15 11:36:16] INFO: { Current stage: 0:02:24.785 || Total: 0:02:24.785 }
[2022-11-15 11:36:16] INFO: [CheckM - lineage_set] Inferring lineage-specific marker sets.
[2022-11-15 11:36:16] INFO: Reading HMM info from file.
[2022-11-15 11:36:16] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 831 of 831 (100.00%) bins.
[2022-11-15 11:36:40] INFO: Determining marker sets for each genome bin.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/home/zoubh/.local/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/zoubh/.local/lib/python3.10/site-packages/checkm/main.py", line 980, in parseOptions
    self.lineageSet(options)
  File "/home/zoubh/.local/lib/python3.10/site-packages/checkm/main.py", line 261, in lineageSet
    treeParser.getBinMarkerSets(options.tree_dir, options.marker_file,
  File "/home/zoubh/.local/lib/python3.10/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/home/zoubh/.local/lib/python3.10/site-packages/dendropy/datamodel/basemodel.py", line 216, in get_from_path
    with open(src, "r", newline=None) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '../AllData/RealDataBinningModels/MaxBin_Data/HLJ/DeepurifyTempOut/FilterOutput/family_filter/checkmTempOut/storage/tree/concatenated.tre

###############
It can not be the out of memory since the memory of my machine is 256GB.
I also checked the log output of pplacer, it seems there is no error in it......
Thanks for answering.

**Comment by azat-badretdin** [comment]
I noticed that the path to the file is relative, which might be a result of specifying relative path in the data installation root. If this is the case, maybe specifying an absolute path could help?

**Comment by zoubohao** [comment]
I appreciate your advice. I'll try using the absolute path to test if this issue persists.

**Comment by zoubohao** [comment]
This issue has been solved. The issue comes from a bug from pplacer. I changed the version of pplacer to the last one and this issue has gone.  

Thanks for giving advices.
