### ISSUE TITLE
checkm lineage_wf ------ BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by PeterCx** [Ecogenomics/CheckM#360]
Hi there,

I am using CheckM to check the completeness and contamination of 12,700 Genome Bins.

This is the code I am using:

checkm lineage_wf -t 1 -x fa Bins CheckM

I get the following error:

Traceback (most recent call last):
  File "/home/peterc/miniconda3/envs/CheckM_env/lib/python3.6/multiprocessing/queues.py", line 240, in _feed
    send_bytes(obj)
  File "/home/peterc/miniconda3/envs/CheckM_env/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/peterc/miniconda3/envs/CheckM_env/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/peterc/miniconda3/envs/CheckM_env/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

No idea what the issue is. I have had a look in the file "connection.py" but I am not sure what to change. Help is greatly appreciated.

Kind regards,

P

**Comment by dparks1134** [comment]
Not sure what the exact issue is, but you may want to break your genomes into smaller batches:
https://github.com/Ecogenomics/CheckM/wiki/Bugs-and-Feature-Requests#processing-large-numbers-of-genomes

**Comment by PeterCx** [comment]
Yes this has solved the issue. Many thanks
