### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sandipandrils** [Ecogenomics/CheckM#373]
I am trying to work on a genome to analyze with checkm with the following commands 

checkm lineage_wf -x fa Galaxy80-\[GCA_009932715.2_ASM993271v2_genomic.fna\].fasta ../CheckM-output/

Got the following error:[2023-05-22 17:57:32] INFO: CheckM v1.2.2
[2023-05-22 17:57:32] INFO: checkm lineage_wf -x fa Galaxy80-[GCA_009932715.2_ASM993271v2_genomic.fna].fasta ../CheckM-output/
[2023-05-22 17:57:32] INFO: CheckM data: /home/sandipan/Work/Anindita/Checkm/
[2023-05-22 17:57:32] INFO: [CheckM - tree] Placing bins in reference genome tree.

Unexpected error: <class 'IndexError'>
Traceback (most recent call last):
  File "/home/sandipan/anaconda3/envs/checkm/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/sandipan/anaconda3/envs/checkm/lib/python3.9/site-packages/checkm/main.py", line 979, in parseOptions
    self.tree(options)
  File "/home/sandipan/anaconda3/envs/checkm/lib/python3.9/site-packages/checkm/main.py", line 141, in tree
    binFiles = self.binFiles(
  File "/home/sandipan/anaconda3/envs/checkm/lib/python3.9/site-packages/checkm/main.py", line 106, in binFiles
    binFile = files[1]
IndexError: list index out of range

Anyone can help. I am new to this. The test worked fine.

**Comment by nelsonruth11** [comment]
You have to specify a directory of genomes instead of a single file. See #346
