### ISSUE TITLE
Chekm test: line 1: 16491 Bus error               (core dumped) pplacer -j 1 

### ISSUE THREAD

**Issue by 98jay** [Ecogenomics/CheckM#379]
Hello, i am running checkm test after the checkm installed. But I got the **error**:
```
[2023-09-11 21:31:17] INFO: Placing 1 bins into the genome tree with pplacer (be patient).
sh: line 1: 16491 Bus error               **(core dumped) pplacer** -j 1 -c /gpfs/share/home/user/software/miniconda3/envs/checkm/checkm_data/genome_tree/genome_tree_reduced.refpkg -o checkm_test_result/results/storage/tree/concatenated.pplacer.json checkm_test_result/results/storage/tree/concatenated.fasta > checkm_test_result/results/storage/tree/pplacer.out
Uncaught exception: Sys_error("checkm_test_result/results/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("checkm_test_result/results/storage/tree/concatenated.pplacer.json: No such file or directory")
```

The details are as followings.
```
 `(checkm) [userlogin checkm]$ checkm data setRoot checkm_data
[2023-09-11 21:30:30] INFO: CheckM v1.2.2
[2023-09-11 21:30:30] INFO: checkm data setRoot checkm_data
[2023-09-11 21:30:30] INFO: CheckM data: /gpfs/share/home/user/software/miniconda3/envs/checkm/checkm_data
[2023-09-11 21:30:30] INFO: [CheckM - data] Check for database updates. [setRoot]
(checkm) [userlogin checkm]$ checkm test checkm_test_result
[2023-09-11 21:30:52] INFO: CheckM v1.2.2
[2023-09-11 21:30:52] INFO: checkm test checkm_test_result
[2023-09-11 21:30:52] INFO: CheckM data: /gpfs/share/home/user/software/miniconda3/envs/checkm/checkm_data
[2023-09-11 21:30:52] INFO: [CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
[2023-09-11 21:30:52] INFO: [Step 1]: Verifying tree command.
[2023-09-11 21:30:52] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2023-09-11 21:30:52] INFO: Identifying marker genes in 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2023-09-11 21:31:13] INFO: Saving HMM info to file.
[2023-09-11 21:31:13] INFO: Calculating genome statistics for 1 bins with 1 threads:
    Finished processing 1 of 1 (100.00%) bins.
[2023-09-11 21:31:14] INFO: Extracting marker genes to align.
[2023-09-11 21:31:14] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.
[2023-09-11 21:31:14] INFO: Extracting 43 HMMs with 1 threads:
    Finished extracting 43 of 43 (100.00%) HMMs.
[2023-09-11 21:31:15] INFO: Aligning 43 marker genes with 1 threads:
    Finished aligning 43 of 43 (100.00%) marker genes.
[2023-09-11 21:31:17] INFO: Reading marker alignment files.
[2023-09-11 21:31:17] INFO: Concatenating alignments.
[2023-09-11 21:31:17] INFO: Placing 1 bins into the genome tree with pplacer (be patient).
sh: line 1: 16491 Bus error               (core dumped) pplacer -j 1 -c /gpfs/share/home/user/software/miniconda3/envs/checkm/checkm_data/genome_tree/genome_tree_reduced.refpkg -o checkm_test_result/results/storage/tree/concatenated.pplacer.json checkm_test_result/results/storage/tree/concatenated.fasta > checkm_test_result/results/storage/tree/pplacer.out
Uncaught exception: Sys_error("checkm_test_result/results/storage/tree/concatenated.pplacer.json: No such file or directory")
Fatal error: exception Sys_error("checkm_test_result/results/storage/tree/concatenated.pplacer.json: No such file or directory")
[2023-09-11 21:32:04] INFO: { Current stage: 0:01:12.118 || Total: 0:01:12.118 }
[2023-09-11 21:32:05] INFO: [Passed]
[2023-09-11 21:32:05] INFO: [Step 2]: Verifying tree_qa command.
[2023-09-11 21:32:05] INFO: [CheckM - tree_qa] Assessing phylogenetic markers found in each bin.
[2023-09-11 21:32:05] INFO: Reading HMM info from file.
[2023-09-11 21:32:05] INFO: Parsing HMM hits to marker genes:
    Finished parsing hits for 1 of 1 (100.00%) bins.

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/main.py", line 1031, in parseOptions
    self.test(options)
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/main.py", line 940, in test
    verifyEcoli.run(self, options.output_dir)
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/test/test_ecoli.py", line 75, in run
    parser.treeQA(options)
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/main.py", line 225, in treeQA
    treeParser.printSummary(
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/treeParser.py", line 45, in printSummary
    self.reportBinTaxonomy(outDir, resultsParser, bTabTable, outFile, binStats, bLineageStatistics=False)
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/treeParser.py", line 641, in reportBinTaxonomy
    binIdToTaxonomy = self.getBinTaxonomy(outDir, binIds)
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/treeParser.py", line 191, in getBinTaxonomy
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
  File "/gpfs/share/home/user/software/miniconda3/envs/checkm/lib/python3.9/site-packages/dendropy/datamodel/basemodel.py", line 217, in get_from_path
    with open(src, *open_args) as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'checkm_test_result/results/storage/tree/concatenated.tre'
(checkm) [userlogin checkm]$ 
`
```

[checkm_test_error.txt](https://github.com/Ecogenomics/CheckM/files/12576951/checkm_test_error.txt)

I tried some suggestions all I could found but it doesn't work. So are there any suggestions? Many thanks!
@donovan-h-parks @donovan-h-parks 
cheers,

**Comment by Debbie142** [comment]
I also have the same problem. Have you solved this issue? Thanks @98jay

**Comment by donovan-h-parks** [comment]
Hi. This is general due to CheckM (or more specifically pplacer) running out of memory. You can find system requirements here:
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements
