### ISSUE TITLE
checkm ssu_finder

### ISSUE THREAD

**Issue by mehmetdayi** [Ecogenomics/CheckM#384]
Dear all,

I am trying to run ssu_finder as below, and errors occurred. Any idea?

`checkm ssu_finder -x fa  36_Inf3_11dpi_metasapdes.metagenome.assembly.fasta `

36_Inf3_11dpi_metasapdes.metagenome.assembly.fasta.metabat-bins ssu_finder
[2024-01-10 15:30:59] INFO: CheckM v1.2.2
[2024-01-10 15:30:59] INFO: checkm ssu_finder -x fa 36_Inf3_11dpi_metasapdes.metagenome.assembly.fasta 36_Inf3_11dpi_metasapdes.metagenome.assembly.fasta.metabat-bins ssu_finder
[2024-01-10 15:30:59] INFO: CheckM data: /home/mdayi/.checkm
[2024-01-10 15:30:59] INFO: [CheckM - ssu_finder] Identifying SSU (16S/18S) rRNAs in sequences.
[2024-01-10 15:31:14] INFO: Determining bin assignment of sequences.
[2024-01-10 15:31:39] INFO: Identifying SSU rRNAs on sequences.
[2024-01-10 15:31:39] INFO: Identifying bacterial 16S.

Error: File existence/permissions problem in trying to open query file /home/mdayi/.checkm/hmms_ssu/SSU_bacteria.hmm.
HMM file /home/mdayi/.checkm/hmms_ssu/SSU_bacteria.hmm not found (nor an .h3m binary of it)

cat: write error: Broken pipe
[2024-01-10 15:31:39] INFO: Identifying archaeal 16S.

Error: File existence/permissions problem in trying to open query file /home/mdayi/.checkm/hmms_ssu/SSU_archaea.hmm.
HMM file /home/mdayi/.checkm/hmms_ssu/SSU_archaea.hmm not found (nor an .h3m binary of it)

cat: write error: Broken pipe
[2024-01-10 15:31:39] INFO: Identifying eukaryotic 18S.

Error: File existence/permissions problem in trying to open query file /home/mdayi/.checkm/hmms_ssu/SSU_euk.hmm.
HMM file /home/mdayi/.checkm/hmms_ssu/SSU_euk.hmm not found (nor an .h3m binary of it)

cat: write error: Broken pipe

Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/home/mdayi/Miniconda3/envs/checkm/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/mdayi/Miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/main.py", line 1027, in parseOptions
    self.ssuFinder(options)
  File "/home/mdayi/Miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/main.py", line 928, in ssuFinder
    ssuFinder.run(options.seq_file, binFiles, options.output_dir,
  File "/home/mdayi/Miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/ssuFinder.py", line 213, in run
    seqInfo = self._readHits(os.path.join(outputDir, 'ssu' + '.' + domain + '.txt'), domain, evalueThreshold)
  File "/home/mdayi/Miniconda3/envs/checkm/lib/python3.9/site-packages/checkm/ssuFinder.py", line 61, in _readHits
    for line in open(resultsFile):
FileNotFoundError: [Errno 2] No such file or directory: 'ssu_finder/ssu.archaea.txt'

**Comment by mehmetdayi** [comment]
`checkm ssu_finder -x fa  36_Inf3_11dpi_metasapdes.metagenome.assembly.fasta  36_Inf3_11dpi_metasapdes.metagenome.assembly.fasta.metabat-bins ssu_finder`

**Comment by mehmetdayi** [comment]
I figured it out. All we need is to locate necessary directories (Error: File existence/permissions problem in trying to open query ) where checkm seeks.
