### ISSUE TITLE
Unexpected error: <class 'FileNotFoundError'>

### ISSUE THREAD

**Issue by zzzzzoeyy** [Ecogenomics/CheckM#391]
Unexpected error: <class 'FileNotFoundError'>
Traceback (most recent call last):
  File "/Users/zhangluyao/anaconda3/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/Users/zhangluyao/anaconda3/lib/python3.11/site-packages/checkm/main.py", line 980, in parseOptions
    self.lineageSet(options)
  File "/Users/zhangluyao/anaconda3/lib/python3.11/site-packages/checkm/main.py", line 261, in lineageSet
    treeParser.getBinMarkerSets(options.tree_dir, options.marker_file,
  File "/Users/zhangluyao/anaconda3/lib/python3.11/site-packages/checkm/treeParser.py", line 485, in getBinMarkerSets
    tree = dendropy.Tree.get_from_path(treeFile, schema='newick', rooting="force-rooted", preserve_underscores=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangluyao/anaconda3/lib/python3.11/site-packages/dendropy/datamodel/basemodel.py", line 217, in get_from_path
    with open(src, *open_args) as fsrc:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/zhangluyao/Downloads/checkm_data_2015_01_16/result/storage/tree/concatenated.tre'

**Comment by donovan-h-parks** [comment]
Hi. Such issues are generally due to CheckM running out of memory. You can check the system requirements here:
https://github.com/Ecogenomics/CheckM/wiki/Installation#system-requirements
