### ISSUE TITLE
ValueError: malformed node or string on line 1: <ast.Call object at 0x71dfb527dfd0>

### ISSUE THREAD

**Issue by yqy6611** [Ecogenomics/CheckM#397]
Hi all, I encountered such error:

Unexpected error: <class 'ValueError'>
Traceback (most recent call last):
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/site-packages/checkm/main.py", line 980, in parseOptions
    self.lineageSet(options)
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/site-packages/checkm/main.py", line 249, in lineageSet
    resultsParser.analyseResults(options.tree_dir,
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/site-packages/checkm/resultsParser.py", line 63, in analyseResults
    binStats = self.parseBinStats(outDir, binStatsFile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/site-packages/checkm/resultsParser.py", line 155, in parseBinStats
    binStats[lineSplit[0]] = ast.literal_eval(lineSplit[1])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/ast.py", line 112, in literal_eval
    return _convert(node_or_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/ast.py", line 101, in _convert
    return dict(zip(map(_convert, node.keys),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/ast.py", line 111, in _convert
    return _convert_signed_num(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/ast.py", line 85, in _convert_signed_num
    return _convert_num(node)
           ^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/ast.py", line 76, in _convert_num
    _raise_malformed_node(node)
  File "/home/e2s2/miniconda3/envs/metawrap-reassembly/lib/python3.12/ast.py", line 73, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string on line 1: <ast.Call object at 0x71dfb527dfd0>

May I know how to solve it? Thanks!

**Comment by azat-badretdin** [comment]
We are seeing this as well.

**Comment by donovan-h-parks** [comment]
This is related to numpy 2.0.0. I will push a new version later today that addresses this.

**Comment by donovan-h-parks** [comment]
This is fixed in v1.2.3.
