### ISSUE TITLE
OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by yqy6611** [Ecogenomics/CheckM#402]
Hi all, 

I encountered this error:

[2024-07-28 08:43:11] INFO: CheckM v1.2.3
[2024-07-28 08:43:11] INFO: checkm lineage_wf -x fa reassembly_nus/reassembled_bins reassembly_nus/reassembled_bins.checkm -t 96 --tmpdir reassembly_nus/tmp --pplacer_threads 22
[2024-07-28 08:43:11] INFO: CheckM data: /mnt/cc061462-beb3-49ab-9318-5c7bf54d8588/database/checkm_database/checkm_data_2015_01_16
[2024-07-28 08:43:11] INFO: [CheckM - tree] Placing bins in reference genome tree.
[2024-07-28 08:43:21] INFO: Identifying marker genes in 609 bins with 96 threads:
Process SyncManager-1:
Traceback (most recent call last):
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/managers.py", line 591, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/managers.py", line 156, in __init__
    self.listener = Listener(address=address, backlog=128)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/connection.py", line 464, in __init__
    self._listener = SocketListener(address, family, backlog)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/connection.py", line 608, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long

Unexpected error: <class 'EOFError'>
Traceback (most recent call last):
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/bin/checkm", line 856, in <module>
    checkmParser.parseOptions(args)
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/site-packages/checkm/main.py", line 979, in parseOptions
    self.tree(options)
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/site-packages/checkm/main.py", line 157, in tree
    binIdToModels = mgf.find(binFiles,
                    ^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/site-packages/checkm/markerGeneFinder.py", line 68, in find
    binIdToModels = mp.Manager().dict()
                    ^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/managers.py", line 566, in start
    self._address = reader.recv()
                    ^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/home/e2s2/miniconda3/envs/metawrap_reassembly/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError

Any ideas on how to fix it? Many thanks!

**Comment by StickHu** [comment]
I just met the error, try to remove the parameter --tmp_dir and it will succeed
