### ISSUE TITLE
bioconda release broken due to setuptools not being shipped with python 3.12 anymore

### ISSUE THREAD

**Issue by njohner** [Ecogenomics/CheckM#403]
When installing the latest bioconda release in a fresh environment, Python 3.12 will get installed and checkm will fail with the following error:

```
Traceback (most recent call last):
  File "/home/njohner/bin/miniconda3/envs/test_checkm/bin/checkm", line 38, in <module>
    from checkm import main
  File "/home/njohner/bin/miniconda3/envs/test_checkm/lib/python3.12/site-packages/checkm/main.py", line 22, in <module>
    from checkm.defaultValues import DefaultValues
  File "/home/njohner/bin/miniconda3/envs/test_checkm/lib/python3.12/site-packages/checkm/defaultValues.py", line 23, in <module>
    from checkm.checkmData import DBManager
  File "/home/njohner/bin/miniconda3/envs/test_checkm/lib/python3.12/site-packages/checkm/checkmData.py", line 25, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
```

`pkg_resources` is [deprecated and removed in Python 3.12](https://docs.python.org/3/whatsnew/3.12.html).

I could fix the issue either by setting the python version to 3.7 or lower or by adding a dependency to `setuptools`.

**Comment by donovan-h-parks** [comment]
A fix for this issue was provided by meereeum and will be part of v1.2.5 which will be released later today.
