### ISSUE TITLE
The coverage.tsv file generated by RefineM is not available for CheckM

### ISSUE THREAD

**Issue by hellopeccat** [Ecogenomics/CheckM#405]
The log is simple:
```
[2024-11-22 20:04:39] INFO: CheckM v1.1.3
[2024-11-22 20:04:39] INFO: checkm profile --tab_table /~/coverage.tsv
[2024-11-22 20:04:39] INFO: [CheckM - profile] Calculating percentage of reads mapped to each bin.
[2024-11-22 20:04:39] INFO: Determining number of reads mapped to each bin.

Unexpected error: <class 'ValueError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 611, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python3.8/dist-packages/checkm/main.py", line 895, in parseOptions
    self.profile(options)
  File "/usr/local/lib/python3.8/dist-packages/checkm/main.py", line 674, in profile
    profile.run(options.coverage_file, options.file, options.bTabTable)
  File "/usr/local/lib/python3.8/dist-packages/checkm/profile.py", line 54, in run
    seqLen = int(lineSplit[2])
ValueError: invalid literal for int() with base 10: '16.77775381509821\n'
```

I have learned that RefineM was not supported any more. However, if this problem could be addressed by a simple way, please give some ideas. Truly, the int value is not included in my coverage.tsv where only contains three column, maybe much less than counterpart generated by checkm ontology:
```
Scaffold Id	Length (bp)	G1.bowtie2.sorted
k141_2260838_length_463684_cov_15.5480	463684	16.77775381509821
k141_1298492_length_558559_cov_30.1468	558559	34.570922677819176
k141_1484042_length_260376_cov_30.0042	260376	36.262228469597815
k141_2244555_length_255226_cov_14.3445	255226	14.59816398015876
```

**Comment by donovan-h-parks** [comment]
Unfortunately RefineM and CheckM v1 are no longer actively supported outside major bug fixes or accepting high value PR.
