### ISSUE TITLE
checkm和pysam都已经安装为正确版本为什么一直报错像图下。

### ISSUE THREAD

**Issue by huang350** [Ecogenomics/CheckM#407]
(checkm3) [yanyi@localhost ~]$ conda list pysam
# packages in environment at /home/hunau/yanyi/LBX/CTRL-C/envs/checkm3:
#
# Name                    Version                   Build  Channel
pysam                     0.22.1           py38h2d19e03_2    bioconda
(checkm3) [yanyi@localhost ~]$ checkm --version
/home/hunau/yanyi/anaconda3/bin/checkm:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('checkm-genome==1.2.3', 'checkm')
Traceback (most recent call last):
  File "/home/hunau/yanyi/anaconda3/bin/checkm", line 4, in <module>
    __import__('pkg_resources').run_script('checkm-genome==1.2.3', 'checkm')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3667, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3651, in _call_aside
    f(*args, **kwargs)
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3680, in _initialize_master_working_set
    working_set = _declare_state('object', 'working_set', WorkingSet._build_master())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    ws.require(__requires__)
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1065, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 892, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 933, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pysam>=0.19.0' distribution was not found and is required by checkm-genome
(checkm3) [yanyi@localhost ~]$ ^C
(checkm3) [yanyi@localhost ~]$ ^C
(checkm3) [yanyi@localhost ~]$ checkm --debug lineage_wf --database /home/hunau/yanyi/.checkm /home/hunau/yanyi/HZY/7个新的
/home/hunau/yanyi/anaconda3/bin/checkm:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('checkm-genome==1.2.3', 'checkm')
Traceback (most recent call last):
  File "/home/hunau/yanyi/anaconda3/bin/checkm", line 4, in <module>
    __import__('pkg_resources').run_script('checkm-genome==1.2.3', 'checkm')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3667, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3651, in _call_aside
    f(*args, **kwargs)
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3680, in _initialize_master_working_set
    working_set = _declare_state('object', 'working_set', WorkingSet._build_master())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    ws.require(__requires__)
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1065, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 892, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/pkg_resources/__init__.py", line 933, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pysam>=0.19.0' distribution was not found and is required by checkm-genome
(checkm3) [yanyi@localhost ~]$ import sys
import: /usr/local/lib/libxml2.so.2: no version information available (required by /lib64/libMagickCore-6.Q16.so.6)
import: /usr/local/lib/libxml2.so.2: no version information available (required by /lib64/libMagickCore-6.Q16.so.6)
import: unable to open X server `' @ error/import.c/ImportImageCommand/344.
(checkm3) [yanyi@localhost ~]$ print(sys.path)
-bash: syntax error near unexpected token `sys.path'
(checkm3) [yanyi@localhost ~]$ python -c "import sys; print(sys.path)"
['', '/home/hunau/yanyi/anaconda3/lib/python312.zip', '/home/hunau/yanyi/anaconda3/lib/python3.12', '/home/hunau/yanyi/anaconda3/lib/python3.12/lib-dynload', '/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages', '/home/hunau/yanyi/anaconda3/lib/python3.12/site-packages/checkm_genome-1.2.3-py3.12.egg']
(checkm3) [yanyi@localhost ~]$ ^C
(checkm3) [yanyi@localhost ~]$

**Comment by donovan-h-parks** [comment]
A fix for pysam was provided by baptwr which will be incorporated into version 1.2.5 which will be released later today.
