### ISSUE TITLE
Filtering of bins in QA plot

### ISSUE THREAD

**Issue by dparks1134** [Ecogenomics/CheckM#45]
Some users have had problems with the bin_qa_plot command as it can't handle large numbers of bins. In the next version of CheckM, we should put in some options to only plot a specific number of the "best" bins.

**Comment by mooreryan** [comment]
I had this problem as well. Got an error when running `bin_qa_plot` on >500 bins, but when I filtered out bins that had < 50% completion (163 bins remaining after filtering), it worked fine.

Here is the error I got:

```
Unexpected error: <type 'exceptions.ValueError'>
Traceback (most recent call last):
  File "/usr/bin/checkm", line 717, in <module>
    checkmParser.parseOptions(args)
  File "/usr/lib/python2.7/site-packages/checkm/main.py", line 1240, in parseOptions
    self.binQAPlot(options)
  File "/usr/lib/python2.7/site-packages/checkm/main.py", line 820, in binQAPlot
    plot.plot(binFiles, binStatsExt, options.bIgnoreHetero, aai.aaiHetero)
  File "/usr/lib/python2.7/site-packages/checkm/plot/binQAPlot.py", line 66, in plot
    xLabelBounds = self.xLabelExtents(sortedBinIds, self.options.font_size)
  File "/usr/lib/python2.7/site-packages/checkm/plot/AbstractPlot.py", line 105, in xLabelExtents
    bbox = label.get_window_extent(self.get_renderer())
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 481, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 94, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
ValueError: width and height must each be below 32768
```

**Comment by dparks1134** [comment]
Deprecated as this plot has been removed from CheckM.
