### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by jinukim** [Ecogenomics/CheckM#52]
Hi

I installed checkm and tried to test using this command line.

> checkm test ~/checkm_test_results

But it printed this error message,
--------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 36, in <module>
    from checkm import main
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 49, in <module>
    from checkm.plot.gcPlots import GcPlots
  File "/usr/local/lib/python2.7/dist-packages/checkm/plot/gcPlots.py", line 24, in <module>
    from AbstractPlot import AbstractPlot
  File "/usr/local/lib/python2.7/dist-packages/checkm/plot/AbstractPlot.py", line 22, in <module>
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_agg.py", line 27, in <module>
    from matplotlib.backend_bases import RendererBase,\
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 50, in <module>
    import matplotlib.textpath as textpath
  File "/usr/lib/pymodules/python2.7/matplotlib/textpath.py", line 11, in <module>
    import matplotlib.font_manager as font_manager
  File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 1356, in <module>
    _rebuild()
  File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 1343, in _rebuild
    pickle_dump(fontManager, _fmcache)
  File "/usr/lib/pymodules/python2.7/matplotlib/font_manager.py", line 939, in pickle_dump
    with open(filename, 'wb') as fh:
IOError: [Errno 2] No such file or directory: '/tmp/matplotlib-Jinu/fontList.cache'
--------------------------------------------------------------------------------------------------------------------

And I tried,
>sudo checkm test ~/checkm_test_results

It printed this message:

--------------------------------------------------------------------------------------------------------------------
*******************************************************************************
[CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
*******************************************************************************

[Step 1]: Verifying tree command.

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  [Error] Make sure prodigal is on your system path.

  Controlled exit resulting from an unrecoverable error or warning.
--------------------------------------------------------------------------------------------------------------------

Because I cannot  run prodigal with sudo.

It's confusing, sorry.

I have all the python packages in the right version.
I am using ubuntu 14.04 on google cloud.

Thanks,

Jinu

**Comment by wwood** [comment]
HI Jinu,

This appears to be an issue with matplotlib rather than checkm. Can you verify that with code outside checkm?

You might also try removing the /tmp/matplotlib-Jinu directory before rerunning checkm test.

Thanks,
ben

**Comment by dparks1134** [comment]
I am assuming this can be closed as there has been on response in over a month.
