### ISSUE TITLE
Error during the useage of checkm lineage_wf

### ISSUE THREAD

**Issue by mghanbari** [Ecogenomics/CheckM#72]
Hi. I followed the instruction for installing the CheckM but when I want to run the following command,  checkm lineage_wf -f SCG_MetaBAT.txt -t 16 -x fa . ./SCG, I got this error.

*******************************************************************************
 [CheckM - tree] Placing bins in reference genome tree.
*******************************************************************************

  Identifying marker genes in 4 bins with 16 threads:
Process Process-3:ssing 0 of 4 (0.00%) bins.
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 307, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 407, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/ngs/hmms/phylo.hmm'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 307, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 407, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/ngs/hmms/phylo.hmm'
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 307, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 407, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/ngs/hmms/phylo.hmm'
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerGeneFinder.py", line 122, in __processBin
    hmmModelFile = markerSetParser.createHmmModelFile(binId, markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 307, in createHmmModelFile
    markerFileType = self.markerFileType(markerFile)
  File "/usr/local/lib/python2.7/dist-packages/checkm/markerSets.py", line 407, in markerFileType
    with open(markerFile, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/home/ngs/hmms/phylo.hmm'

  Saving HMM info to file.

  Calculating genome statistics for 4 bins with 16 threads:
    Finished processing 4 of 4 (100.00%) bins.

  Extracting marker genes to align.
  [Error] Models must be parsed before identifying HMM hits.

Unexpected error: <type 'exceptions.AttributeError'>
Traceback (most recent call last):
  File "/usr/local/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1240, in parseOptions
    self.tree(options)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 152, in tree
    os.path.join(options.out_folder, 'storage', 'tree')
  File "/usr/local/lib/python2.7/dist-packages/checkm/hmmerAligner.py", line 104, in makeAlignmentToPhyloMarkers
    resultsParser.parseBinHits(outDir, hmmTableFile, False, bIgnoreThresholds, evalueThreshold, lengthThreshold)
  File "/usr/local/lib/python2.7/dist-packages/checkm/main.py", line 1201, in parseOptions
    if options.bVerbose:
AttributeError: 'Namespace' object has no attribute 'bVerbose'

Can anyone help me to find out what is the reason of the error?
Thank you

**Comment by dparks1134** [comment]
Hello,

Can you please confirm that you have the following file and that you have
permission to read it:
IOError: [Errno 2] No such file or directory: u'/home/ngs/hmms/phylo.hmm'

Also, can you please verify that you are using the latest version of CheckM
(v1.0.6).

Cheers,
Donovan

**Comment by dparks1134** [comment]
Closed due to inactivity.

**Comment by willnotburn** [comment]
Hi Donovan! I have an identical problem/error. I'm using HMMER/3.1b2 and CheckM/1.0.5

The hmms directory (supposedly where the missing hmms/phylo.hmm should be) does not get created. Should it be? I haven't seen run CheckM successfully and don't know what a good run looks like.

**Comment by dparks1134** [comment]
Hello. The <code>phylo.hmm</code> file is part of the data file package required by CheckM. This can be installed either via FTP or through the CheckM command line interface:
https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm

**Comment by francesco-ricci** [comment]
Hello,

I have the same problem with the hmm folder and phylo.hmm file. I can't find a way to download them. @dparks1134 I can't find them at https://github.com/Ecogenomics/CheckM/wiki/Installation#how-to-install-checkm, would you be able to provide a link to a repository from where I can download them?

Thanks

**Comment by francesco-ricci** [comment]
Solved, thanks I did tar on the folder after gunzip it.

**Comment by TKsh6** [comment]
hello, i got the same problem, could you please tell how to deal with it?
`FileNotFoundError: [Errno 2] No such file or directory: '/beegfs/hom                                            e/syl/.checkm/hmms/phylo.hmm'

[2022-05-02 20:54:52] INFO: Saving HMM info to file.
[2022-05-02 20:54:52] INFO: Calculating genome statistics for 272 bi                                            ns with 36 threads:
    Finished processing 272 of 272 (100.00%) bins.
[2022-05-02 20:54:52] INFO: Extracting marker genes to align.
[2022-05-02 20:54:52] ERROR: Models must be parsed before identifyin                                            g HMM hits.
`

**Comment by TKsh6** [comment]
> Solved, thanks I did tar on the folder after gunzip it.

How did you do it exactly?

**Comment by TKsh6** [comment]
> Hi.
> 
> You need to configure CheckM to be able to locate the additional reference data it depends on: https://github.com/Ecogenomics/CheckM/wiki/Installation#required-reference-data
> 
> Cheers, Donovan

I typed in this command ```checkm test ~/checkm_test_results```to test and I got this:

```
[2022-05-02 22:29:42] INFO: CheckM v1.2.0
[2022-05-02 22:29:42] INFO: checkm test /beegfs/home/syl/checkm_test_results
[2022-05-02 22:29:42] INFO: CheckM data: /beegfs/home/syl/.checkm
[2022-05-02 22:29:42] INFO: [CheckM - Test] Processing E.coli K12-W3310 to verify operation of CheckM.
[2022-05-02 22:29:42] ERROR: Input file does not exists: /beegfs/home/syl/.checkm/test_data/637000110.fna


  Controlled exit resulting from an unrecoverable error or warning.
```
I don't konw why it didn't exist, and I have tried to install checkM through conda, pip3, and even git clone.  Eventually, says "phylo.hmm" didn't exist.

**Comment by dparks1134** [comment]
Have you downloaded the reference data and set the CHECKM_DATA_PATH environmental variable to the directory containing this data?

**Comment by TKsh6** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    I checked the test directory, but i don't konw which one is the test file? For I directicly use the absolute path of the directory, it also reportd "invalid choice".
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 5/2/2022 23:11，Donovan ***@***.***> wrote： 



Have you downloaded the reference data and set the CHECKM_DATA_PATH environmental variable to the directory containing this data?

**Comment by dparks1134** [comment]
Can you try setting the `CHECKM_DATA_PATH` environmental variable to the location of the CheckM reference data?

**Comment by TKsh6** [comment]
How can I do to setting the environmental variable to the location of the CheckM reference data?

**Comment by TKsh6** [comment]
I solved it, thank you:)

**Comment by TKsh6** [comment]
> Oh, would you mind sharing how? I still can't get it right

Firstly，you should download the tar.gz file through [https://data.ace.uq.edu.au/public/CheckM_databases/](url)
Secondly,  you need to unzip this file and place it in the appropriate location
Finally, Try entering these commands:
```
export CHECKM_DATA_PATH=<path to the file>
checkm data setRoot <path to the file>
```
Hope you can make it.
