### ISSUE TITLE
Error running bin_qa_plot

### ISSUE THREAD

**Issue by Sebsnewbie** [Ecogenomics/CheckM#97]
Hi! 
I have run lineage_wf without trouble but get the following error when running  bin_qa_plot for one bin. Thank you for any feedback! 

checkm bin_qa_plot ./checkm_output/ ./checkm_output/bins/database_bin_1 ./plots -x faa

*******************************************************************************
 [CheckM - bin_qa_plot] Creating bar plot of bin quality.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.
  Plotting bin completeness, contamination, and strain heterogeneity.

Unexpected error: <type 'exceptions.KeyError'>
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/checkm_env/bin/checkm", line 712, in <module>
    checkmParser.parseOptions(args)
  File "/home/user/miniconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/main.py", line 1283, in parseOptions
    self.binQAPlot(options)
  File "/home/user/miniconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/main.py", line 848, in binQAPlot
    bMakePlot = plot.plot(binFiles, binStatsExt, options.bIgnoreHetero, aai.aaiHetero)
  File "/home/user/miniconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/plot/binQAPlot.py", line 72, in plot
    sortedBinIds = self.__sortBinsByCompleteness(binFiles, binStatsExt)
  File "/home/user/miniconda3/envs/checkm_env/lib/python2.7/site-packages/checkm/plot/binQAPlot.py", line 45, in __sortBinsByCompleteness
    sortedBinIds.append([binId, binStatsExt[binId]['Completeness']])
KeyError: 'genes'

**Comment by dparks1134** [comment]
Hello,

The issue is with your second parameter (./checkm_output/bins/database_bin_1). This should point to the directory of bins you used when you ran the `lineage_wf` command. I will aim to clarify this in the next release of CheckM.

Cheers,
Donovan

**Comment by Sebsnewbie** [comment]
Thank you!
