### ISSUE TITLE
Error running checkm taxonomy_tw

### ISSUE THREAD

**Issue by DeniRibicic** [Ecogenomics/CheckM#98]
When I run checkm on taxonomy_tw there is  giving back some kind of error. It seems that the process  completes since I have info about completeness and contamination. However taxonomy to bins is not assigned.
Please see the error:

```
 Identifying marker genes in 13 bins with 5 threads:
    Finished processing 13 of 13 (100.00%) bins.
  Saving HMM info to file.

  { Current stage: 0:06:42.607 || Total: 0:06:50.217 }

  Parsing HMM hits to marker genes:
    Finished parsing hits for 13 of 13 (100.00%) bins.
  Aligning marker genes with multiple hits in a single bin:
Process Process-11:sing 1 of 13 (7.69%) bins.
Traceback (most recent call last):
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-8:
Traceback (most recent call last):
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-9:
Traceback (most recent call last):
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 199, in __createMSA
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 199, in __createMSA
    self.run()
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 199, in __createMSA
    self.__alignMarker(markerId, markersWithMultipleHits[markerId], None, False, binAlignOutputDir, tempModelFile, bKeepUnmaskedAlign=False)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 296, in __alignMarker
    self.__maskAlignment(alignSeqFile, makedSeqFile)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 355, in __maskAlignment
    maskedSeq = ''.join([seq[i] for i in xrange(0, len(seq)) if mask[i] == 'x'])
UnboundLocalError: local variable 'mask' referenced before assignment
    self.__alignMarker(markerId, markersWithMultipleHits[markerId], None, False, binAlignOutputDir, tempModelFile, bKeepUnmaskedAlign=False)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 296, in __alignMarker
    self.__maskAlignment(alignSeqFile, makedSeqFile)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 355, in __maskAlignment
    maskedSeq = ''.join([seq[i] for i in xrange(0, len(seq)) if mask[i] == 'x'])
UnboundLocalError: local variable 'mask' referenced before assignment
    self.__alignMarker(markerId, markersWithMultipleHits[markerId], None, False, binAlignOutputDir, tempModelFile, bKeepUnmaskedAlign=False)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 296, in __alignMarker
    self.__maskAlignment(alignSeqFile, makedSeqFile)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 355, in __maskAlignment
    maskedSeq = ''.join([seq[i] for i in xrange(0, len(seq)) if mask[i] == 'x'])
UnboundLocalError: local variable 'mask' referenced before assignment
Process Process-12:
Traceback (most recent call last):
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 199, in __createMSA
    self.__alignMarker(markerId, markersWithMultipleHits[markerId], None, False, binAlignOutputDir, tempModelFile, bKeepUnmaskedAlign=False)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 296, in __alignMarker
    self.__maskAlignment(alignSeqFile, makedSeqFile)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 355, in __maskAlignment
    maskedSeq = ''.join([seq[i] for i in xrange(0, len(seq)) if mask[i] == 'x'])
UnboundLocalError: local variable 'mask' referenced before assignment
Process Process-10:
Traceback (most recent call last):
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/local/home/denir/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 199, in __createMSA
    self.__alignMarker(markerId, markersWithMultipleHits[markerId], None, False, binAlignOutputDir, tempModelFile, bKeepUnmaskedAlign=False)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 296, in __alignMarker
    self.__maskAlignment(alignSeqFile, makedSeqFile)
  File "/local/home/denir/anaconda2/lib/python2.7/site-packages/checkm/hmmerAligner.py", line 355, in __maskAlignment
    maskedSeq = ''.join([seq[i] for i in xrange(0, len(seq)) if mask[i] == 'x'])
UnboundLocalError: local variable 'mask' referenced before assignment
```

I am new to CheckM and still finding my way around, but this has probably to do with my setup. Any help would be appreaciated.

Deni

**Comment by dparks1134** [comment]
Can you send me the command you ran and let me know what version of CheckM you are using?

**Comment by DeniRibicic** [comment]
Hi,
The command:
`checkm taxonomy_wf phylum Proteobacteria input-files checkm-taxonomy-output -x fa -t 5`

The version:  `v1.0.7`

**Comment by dparks1134** [comment]
I'm not sure what the issue is. If you want to send me your bins in a private email (donovan.parks [at] gmail.com) I can debug the issue on my end. Best guess is that one of your genomes is breaking CheckM somehow (e.g., empty FASTA file, sequence header with no actual sequence data), but it could easily just be a long undetected bug. :)

**Comment by dparks1134** [comment]
Well, that isn't very helpful. I can process your genomes with issue on my end:

```
> checkm taxonomy_wf phylum Proteobacteria input-files checkm-taxonomy-output -x fa -t 5

*******************************************************************************
 [CheckM - taxon_set] Generate taxonomic-specific marker set.
*******************************************************************************

  Marker set for Proteobacteria contains 182 marker genes arranged in 119 sets.
    Marker set inferred from 2343 reference genomes.
  Marker set for Bacteria contains 104 marker genes arranged in 58 sets.
    Marker set inferred from 5449 reference genomes.

  Marker set written to: checkm-taxonomy-output/Proteobacteria.ms

  { Current stage: 0:00:08.192 || Total: 0:00:08.192 }

*******************************************************************************
 [CheckM - analyze] Identifying marker genes in bins.
*******************************************************************************

  Identifying marker genes in 13 bins with 5 threads:
    Finished processing 13 of 13 (100.00%) bins.
  Saving HMM info to file.

  { Current stage: 0:05:07.804 || Total: 0:05:15.997 }

  Parsing HMM hits to marker genes:
    Finished parsing hits for 13 of 13 (100.00%) bins.
  Aligning marker genes with multiple hits in a single bin:
    Finished processing 13 of 13 (100.00%) bins.

  { Current stage: 0:00:10.675 || Total: 0:05:26.673 }

  Calculating genome statistics for 13 bins with 5 threads:
    Finished processing 13 of 13 (100.00%) bins.

  { Current stage: 0:00:00.880 || Total: 0:05:27.553 }

*******************************************************************************
 [CheckM - qa] Tabulating genome statistics.
*******************************************************************************

  Calculating AAI between multi-copy marker genes.

  Reading HMM info from file.
  Parsing HMM hits to marker genes:
    Finished parsing hits for 13 of 13 (100.00%) bins.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Bin Id               Marker lineage     # genomes   # markers   # marker sets   0     1    2    3   4   5+   Completeness   Contamination   Strain heterogeneity
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Bin_28_2-contigs   Proteobacteria (1)      2343        182           119        20   149   13   0   0   0       97.48            8.82              100.00                  
... (removed other genomes)        
  Bin_7-contigs      Proteobacteria (1)      2343        182           119        33   145   4    0   0   0       73.74            1.76              75.00                   
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by DeniRibicic** [comment]
Did I get you right, you having the same issue?

**Comment by dparks1134** [comment]
No. It ran without issue on my side.

**Comment by DeniRibicic** [comment]
Yes, as I thought, it something wrong with my setup, but dunno what exactly.
Anyways, if everything would run smoothly, where do I find taxonomy info of the screened bins?

**Comment by dparks1134** [comment]
There is no taxonomy info when you run CheckM using the <code>taxonomy_wf</code>. In this mode, CheckM assumes you are providing the desired/correct taxonomic information.

If you want CheckM to place you genomes into its reference genome tree, you need to use the <code>lineage_wf</code>.

**Comment by DeniRibicic** [comment]
Thanks for clarifying that. Actually I was running that first, still similar error appears.

**Comment by DeniRibicic** [comment]
Okay, the whole day of troubleshooting and frustration I ended up finding out that the pplacer version was 1.0.1. After building > 1.1.0, CheckM works like a charm. 
However I have some questions regarding taxonomy annotation. 
After running `checkm lineage_wf input-files checkm-lineage-output -x fa -t 13`
I've got such output:
```
  Bin Id                      Marker lineage            # genomes   # markers   # marker sets    0     1    2    3   4   5+   Completeness   Contamination   Strain heterogeneity  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  Bin_34-contigs     c__Gammaproteobacteria (UID4444)      263         507           232         23   479   5    0   0   0       98.28            1.01               0.00          
  Bin_28_2-contigs   c__Gammaproteobacteria (UID4443)      356         451           270         27   398   26   0   0   0       97.59            4.32              92.31          
  Bin_14-contigs     c__Gammaproteobacteria (UID4444)      263         507           232         12   485   10   0   0   0       96.84            2.71              40.00          
  Bin_24-contigs     c__Gammaproteobacteria (UID4444)      263         505           231         61   427   15   2   0   0       94.48            4.44              33.33          
  Bin_28_1-contigs   c__Gammaproteobacteria (UID4443)      356         451           270         38   410   3    0   0   0       94.14            0.62              33.33          
  Bin_22-contigs          s__algicola (UID2846)             47         571           303         31   536   4    0   0   0       93.03            0.80              25.00          
  Bin_40-contigs     c__Gammaproteobacteria (UID4761)       52         693           297         45   633   15   0   0   0       92.54            1.42              73.33          
  Bin_21-contigs     c__Gammaproteobacteria (UID4761)       52         693           297         76   596   20   1   0   0       89.42            3.87              78.26          
  Bin_13_2-contigs   c__Gammaproteobacteria (UID4274)      112         581           290         70   499   12   0   0   0       89.26            1.98              83.33          
  Bin_31-contigs     c__Gammaproteobacteria (UID4274)      112         581           290         57   505   19   0   0   0       89.16            3.78              52.63          
  Bin_20-contigs     c__Gammaproteobacteria (UID4761)       52         693           297         86   576   27   1   3   0       87.73            6.22              66.67          
  Bin_26-contigs      f__Flavobacteriaceae (UID2845)        53         548           298        101   442   5    0   0   0       80.25            1.26              100.00         
  Bin_7-contigs      c__Gammaproteobacteria (UID4444)      263         505           231        115   375   14   1   0   0       73.59            3.39              88.24          
--------------------------------------------------------------------------------
```
Is the taxonomy annotated only to class level? Where is the output file containing taxonomy annotation located? I am a bit lost :)
Deni

**Comment by dparks1134** [comment]
Glad you got the program running. The Marker Lineage column indicates where in the tree the marker set was constructed to evaluate the genome. You can get more taxonomic information using the <code>tree_qa</code> command:
https://github.com/Ecogenomics/CheckM/wiki/Genome-Quality-Commands#tree_qa

This includes getting a Newick tree with your genomes placed into CheckM's reference tree. The primary purpose of CheckM is not taxonomic classification though and the reference tree used by CheckM is design with the goal of assessing genome quality. As a consequence, the reference tree contains only high quality referemce genomes.
